### ISSUE TITLE
Twitch API Error 410 (gone)

### ISSUE THREAD

**Issue by mistercaths** [Franiac/TwitchLeecher#403] opened 2019-11-08 20:28 UTC
https://gyazo.com/f488f66726e39af3bc11db3e9d2baa01

Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!

**Comment by Franiac** [comment] 2019-11-08 20:32
See #398 and #402

**Comment by mistercaths** [comment] 2019-11-08 20:41
but it dosent say if theres a fix it says its on twitch ends but is there something i can do? sorry for the bother btw

**Comment by northonyuri** [comment] 2019-11-08 20:55
same problem here uwu

**Comment by Codereaders** [comment] 2019-11-08 22:14
@Franiac seems they introduced a change in the endpoint requirements.
It now no longer requires the client id but an oauth.

Request 1:
```
[GET] https://api.twitch.tv/api/vods/<VIDEO_ID>/access_token
```

Response 1:
```json
{
    "error": "Bad Request",
    "status": 400,
    "message": "No client id specified"
}
```

Request 2:
```
Header: "Client-Id: ....."
[GET] https://api.twitch.tv/api/vods/<VIDEO_ID>/access_token
```

Response 2:
```json
{
    "error": "Gone",
    "status": 410,
    "message": "this API has been removed."
}
```

Request 3 a:
```
Header: "Client-Id: ....."
[GET] https://api.twitch.tv/api/vods/<VIDEO_ID>/access_token?oauth=.....
```

Request 3 b:
```
[GET] https://api.twitch.tv/api/vods/<VIDEO_ID>/access_token?oauth=.....
```

Response 3 a-b:
```json
{
    "token": ".....",
    "sig": ".....",
    "expires_at": "....."
}
```

Might be they experimented with that a few days ago and turned it off and on again.

**Comment by Codereaders** [comment] 2019-11-08 22:29
@mistercaths In case it was a Twitch problem as mentioned [here](https://github.com/Franiac/TwitchLeecher/issues/398#issuecomment-550479989) there is no fix @Franiac could provide.
As it was a temporary thing, it appeared to be a problem on their side. So nothing to do. As it happens repeatedly *and* because of [this](https://github.com/Franiac/TwitchLeecher/issues/403#issuecomment-552010508) it seems very likely that they changed their API and this means that @Franiac could in deed solve the problem by providing an oauth token.
Or better to say, TwitchLeecher has to ask his user for an token.

**Comment by Franiac** [comment] 2019-11-08 23:19
@Codereaders I don't know if you understand what's going on behind the scenes of TL. Without an access token you cannot do anything (e.g. downloading the VOD .m3u8 playlist). TL does indeed retrieve an auth token from the API and uses it. The Client-ID in the header is mandatory. You cannot connect to a wide range of the API without it.

My inbox is kinda exploding right now but I think patience will solve this issue again. My inbox tells me that the whole world will burn to death without TL being immediately fixed by some kind of an unbelievable wonder, but I think that won't happen 😄 

Can anybody really confirm the shutdown schedule for API v5??? I cannot find any statement by Twitch other than v5 is deprecated. v3 was shutdown in September 2019, so I don't think they will torn off v5 anytime soon.

**Comment by Franiac** [comment] 2019-11-08 23:25
how does everybody like my new "patience" label 😈

**Comment by Franiac** [comment] 2019-11-08 23:28
@Codereaders AHA... now I get your comment... I think you read the Helix API documentation. There the authentication workflow is different indeed (no need for a CLient-ID). But TL uses API v5. Just want to clarify that.

**Comment by Franiac** [comment] 2019-11-08 23:47
Even SteamLink is fucked right now:

[https://github.com/streamlink/streamlink/issues/2680](https://github.com/streamlink/streamlink/issues/2680)

So there's something bigger going wrong/on

**Comment by Codereaders** [comment] 2019-11-09 09:56
> Without an access token you cannot do anything (e.g. downloading the VOD .m3u8 playlist).

That's correct, but it seem they changed this endpoint or they are on about to change its behaviour/ requirements. It sometimes behaves as back in the days but also sometimes requires an oauth token. I got a little confused too as it sometimes reacts as back in the days and sometimes not and thought that this was a temporary problem. Inspecting what twitch does on it's website: It seems to always provide the current user's oauth in order to request an access token.

> TL does indeed retrieve an auth token from the API and uses it.

As for what I have seen so far: Sometimes yes, sometimes no.
See 'Endpoint behaviour' below, the auth token is no longer being provided reliably anymore.. ;-)

> The Client-ID in the header is mandatory.

Yes and no. It is true for the official and documented API endpoints.. At least for those that require the client id based on the api description. It might or might not be true for internal APIs that are not meant to be used by developers.

> My inbox is kinda exploding right now but I think patience will solve this issue again. My inbox tells me that the whole world will burn to death without TL being immediately fixed by some kind of an unbelievable wonder, but I think that won't happen smile

Wait, there's no 24/7 availability guaranteed? :D

> **Can anybody really confirm the shutdown schedule for API v5???

v5 is [deprecated but still live in production](https://dev.twitch.tv/docs/product-lifecycle).

> I cannot find any statement by Twitch other than v5 being deprecated.

Correct. To be honest it's not too much of a hassle to migrate TL from kraken (v5) to helix ("new twitch api").


# Endpoint behaviour

## Providing nothing but a video id

Does not work and maybe never did(?):

```bash
$ curl https://api.twitch.tv/api/vods/505577471/access_token
{"error":"Bad Request","status":400,"message":"No client id specified"}
```
## Providing a video id, a client id

Does not work reliably anymore:

```bash
$ curl -H "Client-Id: XXXXXXX" https://api.twitch.tv/api/vods/505577471/access_token
```

Thursday evening
```
{"error":"Bad Request","status":410,"message":"this API has been removed."}
```

Thursday night
```
{"token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[]},\"device_id\":\"XXXXXXXXXXX\",\"expires\":XXXXXXXXXXX,\"https_required\":false,\"privileged\":false,\"user_id\":XXXXXXXXXXX,\"version\":2,\"vod_id\":505577471}","sig": "XXXXXXXXXXX","expires_at": "XXXXXXXXXXX"}
```

Friday evening
```
{"error":"Bad Request","status":410,"message":"this API has been removed."}
```

Saturday morning
```
{"token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[]},\"device_id\":\"XXXXXXXXXXX\",\"expires\":XXXXXXXXXXX,\"https_required\":false,\"privileged\":false,\"user_id\":XXXXXXXXXXX,\"version\":2,\"vod_id\":505577471}","sig": "XXXXXXXXXXX","expires_at": "XXXXXXXXXXX"}
```

## Providing a video id, a client id, an oauth token

Works reliably:

```bash
curl -H "Client-Id: XXXXXXX" https://api.twitch.tv/api/vods/505577471/access_token?oauth=XXXXXX
{"token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[]},\"device_id\":\"XXXXXXXXXXX\",\"expires\":XXXXXXXXXXX,\"https_required\":false,\"privileged\":false,\"user_id\":XXXXXXXXXXX,\"version\":2,\"vod_id\":505577471}","sig": "XXXXXXXXXXX","expires_at": "XXXXXXXXXXX"}
```

## Providing a video id, an oauth token

Works reliably:

```bash
curl https://api.twitch.tv/api/vods/505577471/access_token?oauth=XXXXXX
{"token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[]},\"device_id\":\"XXXXXXXXXXX\",\"expires\":XXXXXXXXXXX,\"https_required\":false,\"privileged\":false,\"user_id\":XXXXXXXXXXX,\"version\":2,\"vod_id\":505577471}","sig": "XXXXXXXXXXX","expires_at": "XXXXXXXXXXX"}
```

**Comment by Franiac** [comment] 2019-11-09 11:42
**As I predicted, everything seems to be working fine again.**

@Codereaders 

> That's correct, but it seem they changed this endpoint or they are on about to change its behaviour/ requirements

That is very very unlikely. Twitch cannot just change a running API (with the exception of adding stuff). That would be a horror scenario for every tool connected to Twitch including StreamLabs, StreamElements and other big companies. The API versioning is there to introduce breaking changes, but they cannot change a running authentication workflow for the year old v5. Twitch devs sometimes are a little bit weird, but they are definitely not borderline stupid 😄

**Comment by Codereaders** [comment] 2019-11-09 12:50
@Franiac 

> Twitch cannot just change a running API (with the exception of adding stuff). That would be a horror scenario for every tool connected to Twitch including StreamLabs, StreamElements and other big companies.

Once again yes and no: For official APIs (kraken, helix) that are explicitly being provided for third parties your expectation is absolutely correct. But you have to keep in mind that there's a huge difference in APIs that are being provided for third parties and those that are not officially provided for third parties.

APIs that are not meant to be used as third parties, often referenced as "inofficial" or "internal" might change without any notification for anyone at any time. Applications that rely on such APIs might break in case Twitch changes those APIs. As they (the APIs) are not meant to be used by third partys usually there's no support at all.

`https://api.twitch.tv/api/` is not an official api endpoint for developers and third parties. It's an api that is meant to be used by Twitch itself, in their apps, on their website etc, but it is not designed to be used by third parties such as streamlabs, TL or what so ever.

> The API versioning is there to introduce breaking changes, but they cannot change a running authentication workflow for the year old v5.

That's true for official APIs. As mentioned before, this might not be true for inofficial ones.

In case you are unsure you should have a look at the [API Reference](https://dev.twitch.tv/docs/v5). v5 is in the link, but helix is not far from there. The reference lists all API endpoints that are meant to be used by third parties. They are easily to recognize by `kraken` (in case of v5) or `helix` (in case of "v6") as a part of the path: `https://api.twitch.tv/helix/....`, `https://api.twitch.tv/kraken/....`

If we're talking about kraken there are two exceptions, but they are explicitly being mentioned in the API reference:

| Endpoint | Description | Where to find | Comment |
| ----------- | -------------- | ----------------- | ------------- |
| https://uploads.twitch.tv/upload/ | Upload for videos | [Video Upload Guide](https://dev.twitch.tv/docs/v5/guides/video-upload), [Upload Video Part](https://dev.twitch.tv/docs/v5/reference/videos#upload-video-part), [Complete Video Upload](https://dev.twitch.tv/docs/v5/reference/videos#complete-video-upload) | - |
| https://api.twitch.tv/v5/channels/ | Manipulate status, game, enable/disable channel feed | [Update Channel > Example Request with a JSON Object](https://dev.twitch.tv/docs/v5/reference/channels#update-channel) | There are some examples that show `kraken` in it's path, and one that shows `v5 ` in it's path. That might be an error or an alias. |

However, this is not a part of v5 / kraken:

```
https://api.twitch.tv/api/vods/<numeric_video_id>/access_token?oauth=XXXXXX
        ^^^^^^^^^^^^^^^^^
```

**Comment by Franiac** [comment] 2019-11-09 17:18
@Codereaders I know how it all comes together. The thing that I try to express is that I don't even want to discuss changes that are 99% temporary. Sure you can do all the tests and try out all the stuff you did with the client id and the auth tokens and such, but now we know it was all in vain since the problem is gone and noone needs to change anything.

I don't want to sound arrogant or anything, but sometimes you just gotta keep calm and chill 😄 
But it's good to know that we have some more "fiddle" people around here who check out stuff when it's really necessary, so I really appreciate that.

Closing this know in the hopes that we don't need to re-open in 3 days.

**Closed by Franiac** 2019-11-09 17:18 UTC
Labels: patience

**Comment by loohhoo** [comment] 2019-11-12 07:09
This has not been fixed - I am having issues downloading vods still and I'm on the newest version. Error 410 (gone). Google pointed me to a reddit thread which then linked here. 

I can download vods totally fine in 4K Video Downloader, so this is definitely something that needs updating on your end.

**Comment by EhsanKia** [comment] 2019-11-17 21:05
I just wanted to quickly add a comment about people saying "It stopped working, but started working again". This is a common pattern Twitch uses when deprecating an API. They will do scheduled downtime. [Here's an example for v3 deprecation](https://discuss.dev.twitch.tv/t/twitch-api-v3-shutdown-timeline/21931). They will start with 15m, then 1 hour, then 6 hours, and so on. This basically is to get apps that rely on these APIs to break and start looking at moving off of the API.

So yeah short term it might start working again, but long term it probably means that they will be killing this endpoint/

**Comment by Troyificus** [comment] 2019-11-22 08:16
I'm getting this error message today. Log is below:

`System.Net.WebException: The remote server returned an error: (410) Gone.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)`

Twitch channel was CriticalRole, if that helps at all.

**Comment by EhsanKia** [comment] 2019-11-22 15:00
It seems like it may be gone for good. Anyone know if there's an official replacement? Can the data be fetched from somewhere else? Has anyone reversed engineered how the website does it now?

**Comment by kyler133** [comment] 2019-11-22 15:01
I am experiencing the same result today.

**Comment by Holgast** [comment] 2020-03-04 10:41
I am having this issue as well.
