### ISSUE TITLE
410 (Gone) (1.7.3)

### ISSUE THREAD

**Issue by eva35** [Franiac/TwitchLeecher#419] opened 2019-11-15 19:12 UTC
Version: 1.7.3 
I am getting this error message again with 1.7.3: 
''An unexpected error occured: 410 (Gone)''

**Comment by Optilasgar** [comment] 2019-11-15 20:22
This is indeed happening for me too, here is a screenshot of the error in question:
https://puu.sh/EEXqw/420ff18529.png

here is the output from the corresponding error log:

System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (410) Nicht vorhanden.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   bei TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by gibmeseeds** [comment] 2019-11-15 20:38
Here is what I got from my error log.

System.Net.WebException: The remote server returned an error: (410) Gone.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by Optilasgar** [comment] 2019-11-15 21:46
yeah, basically the same as me, just in english instead of german

**Comment by Franiac** [comment] 2019-11-15 22:19
Can you guys please be more specific. I cannot read minds.

What do you do?
Where do you click?
When does the error occur?
Are you logged in to TL or not?
Is the video sub-only or not?
Why is Donald Trump an asshole?

**Comment by Optilasgar** [comment] 2019-11-15 22:33
go to a channel that has subscriber only VODs (critical role), click download, be greeted with the 410

1.7.0 - downloading from that channel worked flawlessly
1.7.2 - "cannot download, subscriber only" error, no matter if subscribed via PRIME or regular sub
1.7.3 - 410 (Gone)

**Comment by Optilasgar** [comment] 2019-11-15 22:39
here, made a quick recording of what we are exactly doing:
https://youtu.be/Eo7DrMaaXTI

**Comment by Franiac** [comment] 2019-11-15 22:39
the thing is... today we tested in #416 every variation with multiple users if 1.7.3 works properly. see the last couple comments.

we tested:
- downloading public videos when not logged in
- downloading public videos when logged in
- downlaoding sub-only videos when logged in

all 3 things worked. now they don't work. i honestly think twitch has some kind of time-assisted checks in order to get rid of 3rd party requests from their private API.

If this is true, RIP TL.

What I want to say now: I won't change anything at the moment. Because no matter what I change, it does not work in 2 hours anyway. I honestly don't know where to go from here, sorry

**Comment by eva35** [comment] 2019-11-16 01:12
What do you do? I just followed normal downloading steps.
Where do you click? Download button 
When does the error occur? Since the first time I updated 1.7.3
Are you logged in to TL or not? yes
Is the video sub-only or not? both

**Comment by eva35** [comment] 2019-11-16 01:15
Basically, 1.7.3 is not working for anything. I can not dowload anything in any way.

**Comment by eva35** [comment] 2019-11-16 01:22
So here is another thing, I logged out and it worked for public videos, but when I logged in again it is not working for either sub only and public vods . It is giving 410 error for both.

**Comment by Paticern** [comment] 2019-11-16 01:36
I can confirm the "410 Gone" error as well.

@Franiac The issue in #416 was that the authorization failed because the oauth_token query parameter had the wrong name and/or there was no Authorization header, so I don't think that issue was related tho the "410 Gone" error (the error messages are also different).

If the error persists until later (afternoon/evening UTC+1) I'll try to test which headers are required by the twitch API (similar to what @Codereaders did in #403). Maybe the "Twitch-Api-Token" header or some cookie is required now.

**Comment by Franiac** [comment] 2019-11-16 02:12
@Paticern true, but I am concerned that the changes they make are indeed targeted against 3rd party calls since there is a lot off buzz on the forums about the 410 error and absolute silence from Twitch at the same time. Using the private API for downloading videos is against ToS, so I wouldn't be surprised.

I am not in the position to make big time investments in digging into the new changes at the moment. Real life is more important for me right now.

Here's my 2ct about the current status:

1. Neither we have a clue what causes the API to throw the error right now nor does any other 3rd party dev I know
2. Only logged in requests fail, request without auth tokens work
3. The auth token alone doesn't cut it anymore
4. We can check what makes the request fail by removing headers and parameters one by one
5. If they actually check the request origin, we're fucked (meaning only the twitch website is allowed to call the endpoint)
6. Can we find out if we can obtain a Twitch-API-Token?
7. The cookie contains a lot of Base64 encoded data. What's in there?
8. When soomeone here tests stuff, he needs to make sure that the "old way" does not work at that time

**Comment by Optilasgar** [comment] 2019-11-16 03:10
I know there are browser extensions like VideoDownloadHelper that let me download VODs from subbed channels, if i manually go to the twitch website, navigate to the VOD in question, start playing for at least 1 second, and then am presented with download options.  

Sadly these seem to run out of Sync the longer Videos go on, and are sadly useless to me because of that.

I know this because i tried that when 1.7.2 threw me that you are not subbed line.

**Comment by trivialfabricant** [comment] 2019-11-16 16:24
In case it's useful to know, this issue can be worked around by 1.7.3 users by going to the Twitch connection settings at https://www.twitch.tv/settings/connections and _disconnecting_ Twitch Leecher by scrolling down and clicking "Disconnect", then "Yes, Disconnect".

After doing this, you can now successfully download subscriber-only VoDs (such as from the criticalrole channel some others have mentioned) without getting the 410 (Gone) error. No, I don't understand it either, but there you go!

**Comment by Franiac** [comment] 2019-11-16 16:43
@Optilasgar Twitch extension have the advantage that they run inside the Twitch website and therefor share some of the authentication resources. You cannot compare it to TL which runs completely outside of any Twitch scope.

@trivialfabricant this sounds farely unbelievable. When you disconnect TL it is not capable anymore of checking whether you are subbed to the channel or not. I barely believe your statement (cannot check it, though, because I am not a sub to any channel).

**Comment by red-crate** [comment] 2019-11-16 16:45
@trivialfabricant 
Wow. Its work!
TL 1.7.3 with disconnected from https://www.twitch.tv/settings/connections, i can download it really normally.
However, if i disconnect with TL from https://www.twitch.tv/settings/connections first, i shoud log on there. so This can be used as a temporary measure.

**Comment by red-crate** [comment] 2019-11-16 16:46
@Franiac 
Log on TL 1.7.3 -> disconnect with twitch website -> work
disconnect first -> turn on TL -> ofcourse, doesnt work

**Comment by bbreakthrough** [comment] 2019-11-16 17:19
> In case it's useful to know, this issue can be worked around by 1.7.3 users by going to the Twitch connection settings at https://www.twitch.tv/settings/connections and _disconnecting_ Twitch Leecher by scrolling down and clicking "Disconnect", then "Yes, Disconnect".
> 
> After doing this, you can now successfully download subscriber-only VoDs (such as from the criticalrole channel some others have mentioned) without getting the 410 (Gone) error. No, I don't understand it either, but there you go!



> @Franiac
> Log on TL 1.7.3 -> disconnect with twitch website -> work
> disconnect first -> turn on TL -> ofcourse, doesnt work

This method is does work, for some odd reason.  I'm in the process of downloading the sub-only vod (channel https://www.twitch.tv/criticalrole) that I've been attempting to download since yesterday evening after following the steps provided above.  Perhaps knowing this information can provide you insight on what the issue may be.  Unfortunately I am not terribly proficient in coding, so the best help I can give is to confirm that this method worked for me after receiving the 410 error for nearly 24 hours.

**Comment by Paticern** [comment] 2019-11-16 19:08
@Franiac I have some bad news. I can use the API using the OAuth token which is used by the Twitch website. TL however has a different OAuth token and if I try the same request again using TLs token it fails with the 410 error.

**Comment by Hernan96** [comment] 2019-11-16 19:34
> In case it's useful to know, this issue can be worked around by 1.7.3 users by going to the Twitch connection settings at https://www.twitch.tv/settings/connections and _disconnecting_ Twitch Leecher by scrolling down and clicking "Disconnect", then "Yes, Disconnect".
> 
> After doing this, you can now successfully download subscriber-only VoDs (such as from the criticalrole channel some others have mentioned) without getting the 410 (Gone) error. No, I don't understand it either, but there you go!

What happens if I don't have Twitch Leecher connected to my Twitch account and I want to download a video from non subscriber only VOD (aka everybody can see without subscribing)?

**Comment by trivialfabricant** [comment] 2019-11-16 19:36
> Log on TL 1.7.3 -> disconnect with twitch website -> work
> disconnect first -> turn on TL -> ofcourse, doesnt work
Thank you @red-crate, the first case is an accurate description of what I was doing; I didn't try the second, but I'm sure you are right. Obviously this isn't a sensible way to continue using TL, I just hoped it might help shed some light.

**Comment by Franiac** [comment] 2019-11-16 20:07
@Paticern Thx for the digging! This is exactly what I have feared. Twitch seems to only allow auth tokens that were internally created for Twitch themselves. Every other regular auth token does not get access to the private API anymore, or will be disconnected after a short time.

I still don't get the connection between the website being logged in and TL. The Chromium part of TL cannot read cookies or tokens from the real web browser and vice versa. Even the auth token should be different. I simply don't get how that can be a thing. But apparently this does only work for a short time and then you are back to 410 again.

Currently I have 2 things in mind:

1. We probably have to discontinue the support of sub-only downloads including the whole login system of TL
2. When will Twitch block calls to the private API without an auth token in oder to prohibit public video downloads as well?

**Comment by Optilasgar** [comment] 2019-11-16 20:20
going back to the VideoDownloadHelper. That uses a two pronged approach. It is a combination Chrome Extension and Desktop Companion App, So it intercepts something on the actual website in a standard browser, but that is then handed off somehow to a separately installed windows program.  

Would this be an option?

Have a Twitch Leecher Chrome extension that generates tokens and collects data in some way, and then hands that off to the App in an automated fashion?

**Comment by Paticern** [comment] 2019-11-16 20:24
> We probably have to discontinue the support of sub-only downloads including the whole login system of TL
Personally I would prefer it if I could just paste my token from the website into the config file. Not very user friendly but it should work if TL stops checking the validity of that token.

> I still don't get the connection between the website being logged in and TL. The Chromium part of TL cannot read cookies or tokens from the real web browser and vice versa. Even the auth token should be different. I simply don't get how that can be a thing. But apparently this does only work for a short time and then you are back to 410 again.
1. You authorize TL
2. you revoke the authorization using a browser, TL will still be using the authorization token
3. Twitch somehow accepts this token now for a while (probably some caching issue with their backend)

Speaking of the chromium part of TL: would it be possible to use that to intercept/capture the OAuth token from twitch and use the token from the website for downloads? (this conversation might belong in a separate issue)

**Comment by nitelite** [comment] 2019-11-16 22:10
My thoughts trying to sum up these comments. My most probable reason the auth token suddenly works after removing the connection in the Twitch settings page:

I am guessing that the API for "downloading" does some rudimentary checking of the auth token used when the download requests are made, and they check if the token is connected to a valid "third-party app".

If it is unable to find a valid third-party app attachment, it skips the triggering of the 410 response code. Disconnecting it in the Twitch settings page probably means TL can use it until it expires, but TL will not be able to request a refresh of the token. Removing the "link" through TL/API, on the other hand, removes the locally stored token in TL at the same time (I am guessing), meaning download attempt will no longer have a token to try. 

I do agree with @Franiac that it seems likely that Twitch is actively trying to block third-party token from being able to use this functionality, and this very "race condition" / edge-case bug will probably be fixed in the near future if they realize it's there.

**Comment by Franiac** [comment] 2019-11-16 23:37
@nitelite that's a plausible explanation

@Paticern that's not how I want my software to work. I am giving my best in oder to make a good looking and easy to use software with the time I can spend on it. Implementing hacky and shitty to use workarounds won't happen on my watch, that's not what I do 😄. And @nitelite has a good point why this won't work either anyways.

I am going to see what happens in the next week on the web regarding to this issue and if nothing happens and the situation stays the same, I am going to remove sub-only support.

**Comment by eva35** [comment] 2019-11-17 00:18
Personally, it would be better if you don't remove anything and we could still download sub-only VODs somehow. We can use it one way or another, and we need it.

**Comment by Franiac** [comment] 2019-11-17 01:00
@eva35 this is a nice wish but if you take a closer look at the problems there is no "somehow". i think we all wish it was working again but we do not have many options here. there is no fix so I cannot leave broken features in the software.

**Comment by mtcdood** [comment] 2019-11-17 01:02
An individual I spoke to earlier says this issue affects VODs that are not sub-only as well. 1.7.2 works for them, 1.7.3 returns HTTP 410s.

**Comment by Franiac** [comment] 2019-11-17 01:07
@mtcdood 1.7.3 works with public VODs if you are not logged in...

**Comment by vyperszn** [comment] 2019-11-17 04:56
This software use use to work so good when download sub only videos. why is not working anymore?

**Comment by vyperszn** [comment] 2019-11-17 05:27
Does anyone know which version works well to download sub only videos?

**Comment by MrDummyNL** [comment] 2019-11-17 11:05
1.7.2 is still working with normal VODs. Have not checked 1.7.3 yet but i should test myself with sub-only stream and verify it.

**Comment by Franiac** [comment] 2019-11-17 11:15
@vyperszn There is no version that works with sub-only videos anymore since Twitch blocks 3rd party access since a couple days. There is a high probability that it won't work again anytime in the future. TL will lose sub-only video support in the next version if nothing changes.

**Comment by vyperszn** [comment] 2019-11-17 15:22
@Franiac i was able to download sub only videos on Friday which is two days ago.

**Comment by bhdrozgn** [comment] 2019-11-17 15:40
Version: 1.7.3
Channel: CanSungur ([https://www.twitch.tv/cansungur])
OS: Windows 10 64 Bit

I got this error when i try to download sub-only vods. Yes, i already connected my twitch account and subbed to that channel.
![image](https://user-images.githubusercontent.com/45441291/69009744-7ce7bf00-0969-11ea-821a-2b00dee1eeba.png)

and the log files:
`System.Net.WebException: Uzak sunucu hata döndürdü: (410) Gitti.
   konum: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   konum: System.Net.WebClient.DownloadString(Uri address)
   konum: TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   konum: TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)`

**Comment by Hernan96** [comment] 2019-11-18 01:33
Posting it again since nobody replied.

> > In case it's useful to know, this issue can be worked around by 1.7.3 users by going to the Twitch connection settings at https://www.twitch.tv/settings/connections and _disconnecting_ Twitch Leecher by scrolling down and clicking "Disconnect", then "Yes, Disconnect".
> > After doing this, you can now successfully download subscriber-only VoDs (such as from the criticalrole channel some others have mentioned) without getting the 410 (Gone) error. No, I don't understand it either, but there you go!
> 
> What happens if I don't have Twitch Leecher connected to my Twitch account and I want to download a video from non subscriber only VOD (aka everybody can see without subscribing)? Sorry for the (pretty obvious) noob question.

**Comment by fat-beaver** [comment] 2019-11-18 01:41
I just tried to download a non-sub video (from a channel that has never done sub-only videos, if it matters) and even that is giving the "410 (gone)" error, is it just something at my end or are all downloads now being stopped?

**Comment by Onyx-And-Roman** [comment] 2019-11-18 05:52
I'm unsure how viable this is, but is there any way to say "If you want to download sub-only videos, you must be subbed and logged in, otherwise you must not be logged in" and have that be that? Unless twitch gets angry with you repeatedly verifying thru them, that is a decent workaround for the issue

**Comment by fat-beaver** [comment] 2019-11-18 05:54
I'm not logged in though, so the problem seems to no longer be just an issue with accounts/subs.

**Comment by Franiac** [comment] 2019-11-18 19:40
@fat-beaver I cannot confirm... TL 1.7.3 still works when you are not logged in / downloading public videos

**Comment by Flabbyy** [comment] 2019-11-18 20:17
@Franiac What exactly is the difference between TWITCH_CLIENT_ID, and TWITCH_CLIENT_ID_WEB? When I run a get request on ACCESS_TOKEN_URL, the WEB client ID works, but the normal client ID returns 410. Where is this WEB id coming from? I have seen the exact same ID in multiple github repos

**Comment by Franiac** [comment] 2019-11-18 20:28
@Flabbyy That's the Client ID Twitch uses for their website... but that doesn't help anymore. No Client ID works because they are checking if the auth token was requested by Twitch. Everything else 3rd party related gets rejected.

**Comment by Flabbyy** [comment] 2019-11-18 20:35
@Franiac You're specifically referring to sub-only vods though, right? Or are you saying they will reject all 3rd party vod requests

**Comment by Franiac** [comment] 2019-11-18 20:48
@Flabbyy public videos do not need an auth token and therefor don't use the private API endpoint and therefor are not using the Twitch Client ID 😄 

But I would not be surprised if Twitch also rejects public tokens as well...

**Comment by PolygraphMusic** [comment] 2019-11-18 20:55
I'm really need that ability to download sub-videos.........(((( I'm even gonna donate or buy a premium subscription to the app which can do this... because the streamer I subscribed has a regular account and his streams will be deleted after 14 days and today is the 13th....((

**Comment by Franiac** [comment] 2019-11-18 21:15
@Flabbyy I just realized that my last post is a contradiction in itself, LOL
public videos sure need a token, but those don't get rejected by Twitch (yet).

**Comment by Franiac** [comment] 2019-11-18 21:16
@PolygraphMusic Spamming this issue with non-essential information doesn't make Twitch change their minds.

**Comment by PolygraphMusic** [comment] 2019-11-18 21:25
@Franiac don't spam at all. What "essential" info do You need?

**Comment by Franiac** [comment] 2019-11-18 21:32
@PolygraphMusic If you read this issue in the slightest way (and you should have before posting) you would know that we do not need any information since it is pretty clear that Twitch blocks sub-only downloads and there is nothing to do at the moment. "I need this feature ASAP because blah" posts do not do anything but bloat the issue.

**Comment by PolygraphMusic** [comment] 2019-11-18 21:53
@Franiac Didn't post before, didn't know this. 
Now i understand. 
Will you monitor twitch changes for this issue?

**Comment by Franiac** [comment] 2019-11-18 22:01
there will be a TL 1.8 at the end of the week without sub-only support if nothing changes.
The probability of sub-only downloads ever coming back is minimal and there is a slight probability that TL will stop working completely in the future (not even being able to download public videos anymore).

**Comment by PolygraphMusic** [comment] 2019-11-18 22:04
bad news....
But thanks for clarifying this issue.

**Comment by protoplm** [comment] 2019-11-19 04:07
>     1. You authorize TL
> 
>     2. you revoke the authorization using a browser, TL will still be using the authorization token
> 
>     3. Twitch somehow accepts this token now for a while (probably some caching issue with their backend)

I just wanted to add that this workaround did let me download a couple of sub only VODs that I downloaded this tool for. It probably wont last long as it looks like they are killing the API. Thanks though, it was the only thing that did end up working.

**Comment by Franiac** [comment] 2019-11-19 09:32
@protoplm this was posted 3 times before... the token expires shortly after and becomes unusable

**Comment by Franiac** [comment] 2019-11-19 10:44
Maybe a little light in the dark:

youtube-dl is still able to download sub-only videos (unconfirmed). they do not use the

https://api.twitch.tv/api/vods/{0}/access_token

url to retrieve an auth token but go the official way:

https://dev.twitch.tv/docs/authentication with the endpoint https://id.twitch.tv

maybe we should try this... maybe the auth tokens from the official auth endpoint work.

**Comment by vyperszn** [comment] 2019-11-21 18:48
any update on this? How can change the token and make this sofrware work for 2 hours only?

**Comment by Franiac** [comment] 2019-11-21 19:48
@vyperszn I answered you a couple days ago, this is still valid:

> @vyperszn There is no version that works with sub-only videos anymore since Twitch blocks 3rd party access since a couple days. There is a high probability that it won't work again anytime in the future. TL will lose sub-only video support in the next version if nothing changes.

**Comment by bbreakthrough** [comment] 2019-11-22 05:54
@Franiac 

Not sure if this helps you at all, but Streamlink has two temporary workarounds for the issue.  They also state that they plan on fixing the issue in their next release, so perhaps if they are successful their solution might help you figure it out.

https://github.com/streamlink/streamlink/issues/2680

**Comment by n7alam** [comment] 2019-11-22 06:24
Looks like the streamlink solution is also pointing to using sketchy methods as twitch continues this, it's the beginning of the end. Pre-F to TL, o7. Loved the simple UI.

**Comment by Franiac** [comment] 2019-11-22 11:08
@bbreakthrough I followed the SteamLink issue and they don't have any viable solutions that are really worth checking out.

I think they want to implement the youtube-dl hack. They actually download the Twitch website and parse for the login dialog and such. really messy, really hacky. So they actually pretend to be the Website. Whenever the Twitch website changes, this will fail. Despite the hack being pretty messy, they don't support 2-factor authentication with the Authy app for example.

There are one or two solutions but those are not what I want to have in my software. I know you could say something like: "hey, but it works, so why not", but these implementations are so bad I don't want to deal with them. I want my software to perform well and easy without any greater knowledge the user must gain first in order to use it.

TL is kinda hacky itself since it does something forbidden. But I don't want to overdo it. I hope that is understandable. Sometimes you just have to give Twitch credit for how they protect their streamer's copyrights, you know...

I am not saying there aren't legal and valid usecases for TL. The content creator of Ninja contacted ne for example. So he definitely has the right to download Ninja's VODs but as per the law he does not 😄

**Comment by Franiac** [comment] 2019-11-22 11:10
@n7alam well, we still have the public videos...

**Comment by twin0mega** [comment] 2019-11-23 05:13
I had the same error. Read over some of the responses here and indeed, after I revoked my Twitch login, it all of a sudden worked, no problems. Video was NOT sub-only.

**Comment by Gallion** [comment] 2019-11-25 05:58
Add a field in the options so people can use their own client ID. It's easy enough to find Twitch's own client ID to use with this if it ever changes. This way, you won't have to push out an update every time. I've been using Twitch's client ID in my own Python scripts since this issue has appeared and it has yet to break.

**Comment by Gordon0FreeMan** [comment] 2019-11-25 07:13
Subbed, public broadcast record, trying to download: on version 1.7.3 - error 410, on version 1.7.2 - works perfectly. Rolled back to the previous version.

**Comment by Franiac** [comment] 2019-11-25 10:34
@Gordon0FreeMan Take the 10min of time and read through this issue. 1.7.3 also works on public videos. You just have to log out (no green checkmark). 1.7.2 and 1.7.3 do not work on sub-only videos.

**Comment by zerifu** [comment] 2019-11-26 12:59
i've rolled back to 1.7.2 but he doesnt work on sub videos...says im not subbed to the channel.
i re-login on twitchleecher and twitch and keeps the same issue

**Comment by Franiac** [comment] 2019-11-26 16:01
I am locking this issue now since people are not reading it anyway. If you think you found a fix, please take the time to read this issue from top to bottom and probably you will come across a reason why your fix is not a fix 😄 

TL 1.8 without sub-only support is on the way...

**Comment by Franiac** [comment] 2019-11-27 14:48
TL 1.8 has been released -> closed

**Closed by Franiac** 2019-11-27 14:48 UTC
