### ISSUE TITLE
0x80091007  -the hash value is not correct

### ISSUE THREAD

**Issue by Courageousodin** [Franiac/TwitchLeecher#378] opened 2019-08-17 05:50 UTC
[39BC:04A0][2019-08-17T01:45:17]i001: Burn v3.11.1.2318, Windows v10.0 (Build 17134: Service Pack 0), path: C:\Users\ApoIIo\AppData\Local\Temp\{88CC03DB-1172-4852-A4A7-57E897ABC24F}\.cr\TwitchLeecher_1.7 (1).exe
[39BC:04A0][2019-08-17T01:45:17]i000: Initializing string variable 'BUNDLE_MANUFACTURER' to value 'Franiac'
[39BC:04A0][2019-08-17T01:45:17]i000: Initializing string variable 'BUNDLE_PRODUCT_NAME' to value 'Twitch Leecher'
[39BC:04A0][2019-08-17T01:45:17]i000: Initializing string variable 'BUNDLE_PRODUCT_VERSION_PADDED' to value '1.7.0.0'
[39BC:04A0][2019-08-17T01:45:17]i000: Initializing string variable 'BUNDLE_PRODUCT_VERSION_TRIMMED' to value '1.7'
[39BC:04A0][2019-08-17T01:45:17]i009: Command Line: '"-burn.clean.room=C:\Users\ApoIIo\Downloads\New folder\TwitchLeecher_1.7 (1).exe" -burn.filehandle.attached=600 -burn.filehandle.self=620'
[39BC:04A0][2019-08-17T01:45:17]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\ApoIIo\Downloads\New folder\TwitchLeecher_1.7 (1).exe'
[39BC:04A0][2019-08-17T01:45:17]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\Users\ApoIIo\Downloads\New folder\'
[39BC:04A0][2019-08-17T01:45:17]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\ApoIIo\AppData\Local\Temp\Twitch_Leecher_1.7_20190817014517.log'
[39BC:04A0][2019-08-17T01:45:17]i000: Setting string variable 'WixBundleName' to value 'Twitch Leecher 1.7'
[39BC:04A0][2019-08-17T01:45:17]i000: Setting string variable 'WixBundleManufacturer' to value 'Franiac'
[39BC:04A0][2019-08-17T01:45:17]i000: Loading prerequisite bootstrapper application because managed host could not be loaded, error: 0x80131700.
[39BC:15B8][2019-08-17T01:45:17]i000: Setting numeric variable 'WixStdBALanguageId' to value 1033
[39BC:15B8][2019-08-17T01:45:17]i000: Setting version variable 'WixBundleFileVersion' to value '1.7.0.0'
[39BC:04A0][2019-08-17T01:45:17]i100: Detect begin, 2 packages
[39BC:04A0][2019-08-17T01:45:17]i000: Setting string variable 'NetFxCurrent' to value '461808'
[39BC:04A0][2019-08-17T01:45:17]w120: Detected partially cached package: NetFxWeb, invalid payload: NetFxWeb, reason: 0x80070002
[39BC:04A0][2019-08-17T01:45:17]i052: Condition 'NetFxCurrent >= 528040' evaluates to false.
[39BC:04A0][2019-08-17T01:45:17]i101: Detected package: NetFxWeb, state: Absent, cached: Partial
[39BC:04A0][2019-08-17T01:45:17]i101: Detected package: TL, state: Absent, cached: None
[39BC:04A0][2019-08-17T01:45:17]i199: Detect complete, result: 0x0
[39BC:04A0][2019-08-17T01:45:20]i200: Plan begin, 2 packages, action: Install
[39BC:04A0][2019-08-17T01:45:20]w321: Skipping dependency registration on package with no dependency providers: NetFxWeb
[39BC:04A0][2019-08-17T01:45:20]i000: Setting string variable 'NetFxFullLog' to value 'C:\Users\ApoIIo\AppData\Local\Temp\Twitch_Leecher_1.7_20190817014517_000_NetFxWeb.log'
[39BC:04A0][2019-08-17T01:45:20]i201: Planned package: NetFxWeb, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: None, cache: Yes, uncache: No, dependency: None
[39BC:04A0][2019-08-17T01:45:20]i201: Planned package: TL, state: Absent, default requested: Present, ba requested: None, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[39BC:04A0][2019-08-17T01:45:20]i299: Plan complete, result: 0x0
[39BC:04A0][2019-08-17T01:45:20]i300: Apply begin
[39BC:04A0][2019-08-17T01:45:20]i010: Launching elevated engine process.
[39BC:04A0][2019-08-17T01:45:27]i011: Launched elevated engine process.
[39BC:04A0][2019-08-17T01:45:27]i012: Connected to elevated engine.
[3860:2DA4][2019-08-17T01:45:27]i358: Pausing automatic updates.
[3860:2DA4][2019-08-17T01:45:27]i359: Paused automatic updates.
[3860:2DA4][2019-08-17T01:45:27]i360: Creating a system restore point.
[3860:2DA4][2019-08-17T01:46:33]i361: Created a system restore point.
[3860:2DA4][2019-08-17T01:46:33]i370: Session begin, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, options: 0x7, disable resume: No
[3860:2DA4][2019-08-17T01:46:33]i000: Caching bundle from: 'C:\Users\ApoIIo\AppData\Local\Temp\{540AAAE1-CB20-42AC-9FA4-1AB231375A13}\.be\TwitchLeecher.exe' to: 'C:\ProgramData\Package Cache\{d1c2c779-f1ef-41e0-926a-443b289eaefd}\TwitchLeecher.exe'
[3860:2DA4][2019-08-17T01:46:33]i320: Registering bundle dependency provider: {d1c2c779-f1ef-41e0-926a-443b289eaefd}, version: 1.7.0.0
[3860:2DA4][2019-08-17T01:46:33]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: Active, restart initiated: No, disable resume: No
[39BC:3D1C][2019-08-17T01:46:33]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: C:\Users\ApoIIo\Downloads\New folder\ndp48-web.exe
[39BC:3D1C][2019-08-17T01:46:33]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
[3860:3F18][2019-08-17T01:46:35]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
[3860:3F18][2019-08-17T01:46:35]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
[3860:3F18][2019-08-17T01:46:35]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
[3860:3F18][2019-08-17T01:46:35]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
[39BC:3D1C][2019-08-17T01:46:35]e314: Failed to cache payload: NetFxWeb from working path: C:\Users\ApoIIo\AppData\Local\Temp\{540AAAE1-CB20-42AC-9FA4-1AB231375A13}\NetFxWeb, error: 0x80091007.
[39BC:3D1C][2019-08-17T01:46:35]e349: Application requested retry of payload: NetFxWeb, encountered error: 0x80091007. Retrying...
[39BC:3D1C][2019-08-17T01:46:35]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: C:\Users\ApoIIo\Downloads\New folder\ndp48-web.exe
[39BC:3D1C][2019-08-17T01:46:38]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
[3860:3F18][2019-08-17T01:46:39]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
[3860:3F18][2019-08-17T01:46:39]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
[3860:3F18][2019-08-17T01:46:39]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
[3860:3F18][2019-08-17T01:46:39]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
[39BC:3D1C][2019-08-17T01:46:39]e314: Failed to cache payload: NetFxWeb from working path: C:\Users\ApoIIo\AppData\Local\Temp\{540AAAE1-CB20-42AC-9FA4-1AB231375A13}\NetFxWeb, error: 0x80091007.
[39BC:3D1C][2019-08-17T01:46:39]e349: Application requested retry of payload: NetFxWeb, encountered error: 0x80091007. Retrying...
[39BC:3D1C][2019-08-17T01:46:39]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: C:\Users\ApoIIo\Downloads\New folder\ndp48-web.exe
[39BC:3D1C][2019-08-17T01:46:42]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
[3860:3F18][2019-08-17T01:46:43]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
[3860:3F18][2019-08-17T01:46:43]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
[3860:3F18][2019-08-17T01:46:43]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
[3860:3F18][2019-08-17T01:46:43]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
[39BC:3D1C][2019-08-17T01:46:43]e314: Failed to cache payload: NetFxWeb from working path: C:\Users\ApoIIo\AppData\Local\Temp\{540AAAE1-CB20-42AC-9FA4-1AB231375A13}\NetFxWeb, error: 0x80091007.
[39BC:04A0][2019-08-17T01:46:43]e000: Error 0x80091007: Failed while caching, aborting execution.
[3860:2DA4][2019-08-17T01:46:43]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: None, restart: None, disable resume: No
[3860:2DA4][2019-08-17T01:46:43]i330: Removed bundle dependency provider: {d1c2c779-f1ef-41e0-926a-443b289eaefd}
[3860:2DA4][2019-08-17T01:46:43]i352: Removing cached bundle: {d1c2c779-f1ef-41e0-926a-443b289eaefd}, from path: C:\ProgramData\Package Cache\{d1c2c779-f1ef-41e0-926a-443b289eaefd}\
[3860:2DA4][2019-08-17T01:46:43]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: None, restart initiated: No, disable resume: No
[39BC:04A0][2019-08-17T01:46:44]i399: Apply complete, result: 0x80091007, restart: None, ba requested restart:  No

**Comment by mrazeja7** [comment] 2019-08-17 12:14
That's caused by the .NET 4.8 portion of the installer. You can install .NET on its own, then the TL installer works just fine.

Download .NET 4.8 here: https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by Franiac** [comment] 2019-08-17 13:51
Yup, the hash code provided in the TL installer to check the downloaded .NET 4.8 web installer is wrong.
I have already corrected that. Will be fixed in the next version of TL.

**Closed by Franiac** 2019-08-17 13:51 UTC
Labels: bug

**Comment by dokoham** [comment] 2019-08-24 20:29
[2C88:2CA8][2019-08-25T04:26:34]i001: Burn v3.11.1.2318, Windows v10.0 (Build 17134: Service Pack 0), path: C:\WINDOWS\Temp\{EBEE020F-6F34-47C4-9DDE-F3915A3C7A23}\.cr\TwitchLeecher_1.7.exe
[2C88:2CA8][2019-08-25T04:26:34]i000: Initializing string variable 'BUNDLE_MANUFACTURER' to value 'Franiac'
[2C88:2CA8][2019-08-25T04:26:34]i000: Initializing string variable 'BUNDLE_PRODUCT_NAME' to value 'Twitch Leecher'
[2C88:2CA8][2019-08-25T04:26:34]i000: Initializing string variable 'BUNDLE_PRODUCT_VERSION_PADDED' to value '1.7.0.0'
[2C88:2CA8][2019-08-25T04:26:34]i000: Initializing string variable 'BUNDLE_PRODUCT_VERSION_TRIMMED' to value '1.7'
[2C88:2CA8][2019-08-25T04:26:34]i009: Command Line: '-burn.clean.room=C:\Users\Administrator\Desktop\TwitchLeecher_1.7.exe -burn.filehandle.attached=584 -burn.filehandle.self=656'
[2C88:2CA8][2019-08-25T04:26:34]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\Administrator\Desktop\TwitchLeecher_1.7.exe'
[2C88:2CA8][2019-08-25T04:26:34]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\Users\Administrator\Desktop\'
[2C88:2CA8][2019-08-25T04:26:34]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\ADMINI~1\AppData\Local\Temp\Twitch_Leecher_1.7_20190825042634.log'
[2C88:2CA8][2019-08-25T04:26:34]i000: Setting string variable 'WixBundleName' to value 'Twitch Leecher 1.7'
[2C88:2CA8][2019-08-25T04:26:34]i000: Setting string variable 'WixBundleManufacturer' to value 'Franiac'
[2C88:2CA8][2019-08-25T04:26:34]i000: Loading prerequisite bootstrapper application because managed host could not be loaded, error: 0x80131700.
[2C88:2F74][2019-08-25T04:26:34]i000: Setting numeric variable 'WixStdBALanguageId' to value 2052
[2C88:2F74][2019-08-25T04:26:34]i000: Setting version variable 'WixBundleFileVersion' to value '1.7.0.0'
[2C88:2CA8][2019-08-25T04:26:34]i100: Detect begin, 2 packages
[2C88:2CA8][2019-08-25T04:26:34]i000: Setting string variable 'NetFxCurrent' to value '461808'
[2C88:2CA8][2019-08-25T04:26:34]i102: Detected related bundle: {8db3ac0e-bbba-4b04-a5d5-d9b353bb6030}, type: Upgrade, scope: PerMachine, version: 1.5.6.0, operation: MajorUpgrade
[2C88:2CA8][2019-08-25T04:26:34]w120: Detected partially cached package: NetFxWeb, invalid payload: NetFxWeb, reason: 0x80070002
[2C88:2CA8][2019-08-25T04:26:34]i052: Condition 'NetFxCurrent >= 528040' evaluates to false.
[2C88:2CA8][2019-08-25T04:26:34]i103: Detected related package: {4E2BCEDA-504B-4D80-8B59-7B30D634C3B9}, scope: PerMachine, version: 1.5.6.0, language: 0 operation: MajorUpgrade
[2C88:2CA8][2019-08-25T04:26:34]i101: Detected package: NetFxWeb, state: Absent, cached: Partial
[2C88:2CA8][2019-08-25T04:26:34]i101: Detected package: TL, state: Absent, cached: None
[2C88:2CA8][2019-08-25T04:26:34]i199: Detect complete, result: 0x0
[2C88:2CA8][2019-08-25T04:26:38]i200: Plan begin, 2 packages, action: Install
[2C88:2CA8][2019-08-25T04:26:38]i202: Planned bundle: {8db3ac0e-bbba-4b04-a5d5-d9b353bb6030}, ba requested state: None over default: Absent
[2C88:2CA8][2019-08-25T04:26:38]w321: Skipping dependency registration on package with no dependency providers: NetFxWeb
[2C88:2CA8][2019-08-25T04:26:38]i000: Setting string variable 'NetFxFullLog' to value 'C:\Users\ADMINI~1\AppData\Local\Temp\Twitch_Leecher_1.7_20190825042634_000_NetFxWeb.log'
[2C88:2CA8][2019-08-25T04:26:38]i201: Planned package: NetFxWeb, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: None, cache: Yes, uncache: No, dependency: None
[2C88:2CA8][2019-08-25T04:26:38]i201: Planned package: TL, state: Absent, default requested: Present, ba requested: None, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[2C88:2CA8][2019-08-25T04:26:38]i207: Planned related bundle: {8db3ac0e-bbba-4b04-a5d5-d9b353bb6030}, type: Upgrade, default requested: Absent, ba requested: None, execute: None, rollback: None, dependency: None
[2C88:2CA8][2019-08-25T04:26:38]i299: Plan complete, result: 0x0
[2C88:2CA8][2019-08-25T04:26:38]i300: Apply begin
[2C88:2CA8][2019-08-25T04:26:38]i010: Launching elevated engine process.
[2C88:2CA8][2019-08-25T04:26:38]i011: Launched elevated engine process.
[2C88:2CA8][2019-08-25T04:26:38]i012: Connected to elevated engine.
[33A4:285C][2019-08-25T04:26:38]i358: Pausing automatic updates.
[33A4:285C][2019-08-25T04:26:38]i359: Paused automatic updates.
[33A4:285C][2019-08-25T04:26:38]i360: Creating a system restore point.
[33A4:285C][2019-08-25T04:26:38]w363: Could not create system restore point, error: 0x80070422. Continuing...
[33A4:285C][2019-08-25T04:26:38]i370: Session begin, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, options: 0x7, disable resume: No
[33A4:285C][2019-08-25T04:26:38]i000: Caching bundle from: 'C:\WINDOWS\Temp\{54E4E50C-3002-4B31-A6A1-3D4F9C78ADB9}\.be\TwitchLeecher.exe' to: 'C:\ProgramData\Package Cache\{d1c2c779-f1ef-41e0-926a-443b289eaefd}\TwitchLeecher.exe'
[33A4:285C][2019-08-25T04:26:39]i320: Registering bundle dependency provider: {d1c2c779-f1ef-41e0-926a-443b289eaefd}, version: 1.7.0.0
[33A4:285C][2019-08-25T04:26:39]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: Active, restart initiated: No, disable resume: No
[2C88:1960][2019-08-25T04:26:45]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: C:\Users\Administrator\Desktop\ndp48-web.exe
[2C88:1960][2019-08-25T04:26:45]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
[33A4:2F08][2019-08-25T04:26:47]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
[33A4:2F08][2019-08-25T04:26:47]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
[33A4:2F08][2019-08-25T04:26:47]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
[33A4:2F08][2019-08-25T04:26:47]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
[2C88:1960][2019-08-25T04:26:47]e314: Failed to cache payload: NetFxWeb from working path: C:\WINDOWS\Temp\{54E4E50C-3002-4B31-A6A1-3D4F9C78ADB9}\NetFxWeb, error: 0x80091007.
[2C88:1960][2019-08-25T04:26:47]e349: Application requested retry of payload: NetFxWeb, encountered error: 0x80091007. Retrying...
[2C88:1960][2019-08-25T04:26:47]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: C:\Users\Administrator\Desktop\ndp48-web.exe
[2C88:1960][2019-08-25T04:26:50]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
[33A4:2F08][2019-08-25T04:26:51]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
[33A4:2F08][2019-08-25T04:26:51]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
[33A4:2F08][2019-08-25T04:26:51]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
[33A4:2F08][2019-08-25T04:26:51]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
[2C88:1960][2019-08-25T04:26:51]e314: Failed to cache payload: NetFxWeb from working path: C:\WINDOWS\Temp\{54E4E50C-3002-4B31-A6A1-3D4F9C78ADB9}\NetFxWeb, error: 0x80091007.
[2C88:1960][2019-08-25T04:26:51]e349: Application requested retry of payload: NetFxWeb, encountered error: 0x80091007. Retrying...
[2C88:1960][2019-08-25T04:26:51]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: C:\Users\Administrator\Desktop\ndp48-web.exe
[2C88:1960][2019-08-25T04:26:54]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
[33A4:2F08][2019-08-25T04:26:55]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
[33A4:2F08][2019-08-25T04:26:55]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
[33A4:2F08][2019-08-25T04:26:55]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
[33A4:2F08][2019-08-25T04:26:55]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
[2C88:1960][2019-08-25T04:26:55]e314: Failed to cache payload: NetFxWeb from working path: C:\WINDOWS\Temp\{54E4E50C-3002-4B31-A6A1-3D4F9C78ADB9}\NetFxWeb, error: 0x80091007.
[2C88:2CA8][2019-08-25T04:26:55]e000: Error 0x80091007: Failed while caching, aborting execution.
[33A4:285C][2019-08-25T04:26:55]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: None, restart: None, disable resume: No
[33A4:285C][2019-08-25T04:26:55]i330: Removed bundle dependency provider: {d1c2c779-f1ef-41e0-926a-443b289eaefd}
[33A4:285C][2019-08-25T04:26:55]i352: Removing cached bundle: {d1c2c779-f1ef-41e0-926a-443b289eaefd}, from path: C:\ProgramData\Package Cache\{d1c2c779-f1ef-41e0-926a-443b289eaefd}\
[33A4:285C][2019-08-25T04:26:55]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: None, restart initiated: No, disable resume: No
[2C88:2CA8][2019-08-25T04:26:55]i399: Apply complete, result: 0x80091007, restart: None, ba requested restart:  No

**Comment by dokoham** [comment] 2019-08-24 20:29
help please...

**Comment by dokoham** [comment] 2019-08-24 20:29
Please help...it cannot install 4.8 framework
every time  error

**Comment by clb92** [comment] 2019-09-19 08:02
I have this same error with the 1.7 installer now.
