### ISSUE TITLE
Can't Download VOD's

### ISSUE THREAD

**Issue by uaxiii** [Franiac/TwitchLeecher#349] opened 2019-06-29 11:11 UTC
I'm still getting the same problem:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 444722607
Selected Quality: 1600x900@60fps (Source)
Download Url: https://www.twitch.tv/videos/444722607
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\epstein_2\Downloads\20190626_444722607_Sonic Adventure 2.mp4
FFMPEG Path: C:\Users\epstein_2\Downloads\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\epstein_2\AppData\Local\Temp\TL_0f00a74f-3ec6-4975-a483-8596daecf935

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561878489%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A444722607%7D
Signature: 8c022ed3041e5387d19fd976b0c063af0ec0e215
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\epstein_2\AppData\Local\Temp\TL_0f00a74f-3ec6-4975-a483-8596daecf935'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\epstein_2\AppData\Local\Temp\TL_0f00a74f-3ec6-4975-a483-8596daecf935'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

Does anyone know how to fix it?

**Comment by rebugmvm** [comment] 2019-06-29 15:13
so it appears that twitch is either blocking us or your isp is blocking u from downloading im using a vpn and its working like it should.

**Comment by Sagenod** [comment] 2019-06-30 02:23
Had the same issue. Using a VPN worked, does that pretty much mean that it's my ISP blocking me from downloading VODs directly from twitch?

**Comment by Franiac** [comment] 2019-07-02 13:42
Duplicate of #345

**Closed by Franiac** 2019-07-02 13:42 UTC
Labels: duplicate
