### ISSUE TITLE
Feature request: Download to multiple small files instead of 1 big file

### ISSUE THREAD

**Issue by underscorenorm** [Franiac/TwitchLeecher#470] opened 2020-02-25 15:05 UTC
Give the user the option to set the time chunk size and whether or not to merge when download is complete. If I leech a 5 hour stream, let me specify to split it every 30 minutes and have 10 video files. Not sure how much work this is, but I am using video for editing and smaller files makes it easier! I thought about interrupting the download, but the chunks all appear to be 9 seconds long, a little too short to work with. If it's not feasible no big deal, just a nice-to-have.

**Comment by Franiac** [comment] 2020-02-25 17:11
Duplicate of #335

**Closed by Franiac** 2020-02-25 17:11 UTC
Labels: duplicate
