### ISSUE TITLE
Option to download all new recordings

### ISSUE THREAD

**Issue by rvgate** [Franiac/TwitchLeecher#128] opened 2017-04-26 01:03 UTC
Have an option to select all recordings that you have not previously downloaded before.

**Comment by Franiac** [comment] 2017-04-27 15:56
Duplicate of #76

**Closed by Franiac** 2017-04-27 15:56 UTC
Labels: duplicate

**Comment by rvgate** [comment] 2017-05-01 09:44
@Franiac, i don't agree that this is a duplicate. The other ticket states that you can download between or from a certain date... This request is based on if you have downloaded the VOD before (aka, skip if you already have it)

**Comment by Franiac** [comment] 2017-05-01 13:05
Please read the comments of #76
