### ISSUE TITLE
Download subscriber-only VODs

### ISSUE THREAD

**Issue by SDraconis** [Franiac/TwitchLeecher#35] opened 2016-06-04 18:35 UTC
This is a request to re-open #8 . This is currently my only use-case for a Twitch downloader (i.e. the only VODs I wish to download are subscriber-only on channels for which I am a subscriber).

**Comment by Franiac** [comment] 2016-06-06 16:34
I'd like to support this, but first I want to get rid of some relics in the code and implement a few other features that are more important. But since this is the 2nd request I'll leave this issue open.

**Comment by Franiac** [comment] 2016-06-06 16:36
Duplicate of #8

**Closed by Franiac** 2016-06-06 16:36 UTC
Labels: duplicate
