### ISSUE TITLE
Error in all my downloads

### ISSUE THREAD

**Issue by PeryGamerYT** [Franiac/TwitchLeecher#355] opened 2019-07-03 23:09 UTC
Hi im from mexico so my english is bad, i have an issue with twitch leecher, when i start a download i get an error and i dont know why.
I hope you can help me. 

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.5

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 444649377
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/videos/444649377
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Hector Fabian\Downloads\20190626_444649377_Grand Theft Auto V.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Hector Fabian\AppData\Local\Temp\TL_41d89b95-0a74-40bf-811b-ece183a4ca98

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562266807%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A444649377%7D
Signature: 0a86d4dd9d6bac5b5fa90d2e19268bf255cc365f
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Hector Fabian\AppData\Local\Temp\TL_41d89b95-0a74-40bf-811b-ece183a4ca98'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Hector Fabian\AppData\Local\Temp\TL_41d89b95-0a74-40bf-811b-ece183a4ca98'... done!

Download task ended with an error!

System.AggregateException: Se han producido uno o varios errores. ---> System.Net.WebException: Error en el servidor remoto: (404) No se encontró.
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   en System.Net.WebClient.DownloadString(Uri address)
   en TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   en TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   en System.Threading.Tasks.Task.Execute()
   --- Fin del seguimiento de la pila de la excepción interna ---
---> (Nº de excepción interna 0) System.Net.WebException: Error en el servidor remoto: (404) No se encontró.
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   en System.Net.WebClient.DownloadString(Uri address)
   en TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   en TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   en System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment] 2019-07-03 23:12
Duplicate of #345

**Closed by Franiac** 2019-07-03 23:12 UTC
Labels: duplicate

**Comment by PeryGamerYT** [comment] 2019-07-03 23:19
i still having the same problem how can i solve it?
