### ISSUE TITLE
can't download vods anymore

### ISSUE THREAD

**Issue by nscwalk** [Franiac/TwitchLeecher#351] opened 2019-06-29 23:28 UTC
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 445514501
Selected Quality: 1600x900@60fps (Source)
Download Url: https://www.twitch.tv/videos/445514501
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: K:\Twitch Vods\20190628_445514501_Apex Legends.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: K:\New folder (2)\TL_1f96f5e2-4974-4a4f-b1a2-f514e290c82d

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561922863%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A39446403%2C%22version%22%3A2%2C%22vod_id%22%3A445514501%7D
Signature: 9d05bbc325e1b6f4adc7e70817f114d1a91ccccf
Sub-Only: No
Privileged: No

Creating temporary download directory 'K:\New folder (2)\TL_1f96f5e2-4974-4a4f-b1a2-f514e290c82d'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'K:\New folder (2)\TL_1f96f5e2-4974-4a4f-b1a2-f514e290c82d'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Sagenod** [comment] 2019-06-30 02:21
Having the same issue today.  Haven't used twitch leecher in a few months.

**Comment by gorogun** [comment] 2019-07-02 02:38
same here. Since friday I guess :(

**Comment by Franiac** [comment] 2019-07-02 13:43
Duplicate of #345

**Closed by Franiac** 2019-07-02 13:43 UTC
Labels: duplicate
