### ISSUE TITLE
can't download vods

### ISSUE THREAD

**Issue by rebugmvm** [Franiac/TwitchLeecher#348] opened 2019-06-29 04:34 UTC
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 445398818
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/445398818
Crop Start: Yes (01:34:00)
Crop End: Yes (02:24:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: E:\Shiphtur\Todays vid\20190628_445398818_League of Legends.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\15629\AppData\Local\Temp\TL_079fe86d-86e9-4e83-b388-c1343307b470

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561854616%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A445398818%7D
Signature: 07d115bb74e17edc5738faece96bd3a297e26915
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\15629\AppData\Local\Temp\TL_079fe86d-86e9-4e83-b388-c1343307b470'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\15629\AppData\Local\Temp\TL_079fe86d-86e9-4e83-b388-c1343307b470'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by brevii** [comment] 2019-06-29 07:44
Getting the same problem here, downloaded a VOD earlier today and it worked fine, problem started around 8-10 hours ago.

**Comment by Franiac** [comment] 2019-07-02 13:42
Duplicate of #345

**Closed by Franiac** 2019-07-02 13:42 UTC
Labels: duplicate
