### ISSUE TITLE
When the Authorize twitch account button is pressed it does nothing. 

### ISSUE THREAD

**Issue by MrBigfootX** [Franiac/TwitchLeecher#367] opened 2019-07-26 00:12 UTC
I am able to log in and get to the page that says "Authorize" or "Cancel" However when I click the authorize button nothing happens. It just stays on the same screen and no green check mark appears.  I have tried doing it into a browser which then connects Twitch Leecher to my account but the application still says I need authorization. I have already tried uninstalling and re downloading, etc. I am using the latest version of the program.

**Comment by Ravarix** [comment] 2019-07-26 07:04
I am also having this issue. I had it back with a 1.3 and then updated to 1.6 and still had the issue, so I suspect that something has changed on twitches side.

**Comment by PallasWapiti** [comment] 2019-07-26 08:59
Same here unfortunately. Had the problem, in 1.4.7, updated to the latest version, no change.

**Comment by KillTheCube10** [comment] 2019-07-26 11:36
I also had this issue. Then I followed another issue's solution, where you open the authorization in the browser, which let me authorize, but then said it couldn't find the www.tl.com website, Twitch Leecher is listed under connected programs in my twitch settings, but the app doesn't recognize that.

**Comment by Franiac** [comment] 2019-07-26 13:47
I can confirm the issue.

www.tl.com is the redirect url vor the auth process where applications get the token send to. It is not a website or whatever. Just stop trying to manually force TL to connect, it won't work and it's ok that it does not work.

This issue has occured in the past and it solved itself every time within 2-3 days. In the past it was all a Twitch fuckup and I assume it is the same thing this time. Just be patient, please.

I can also confirm that the code responsible for the authentication has not changed since TL 1.4. 
The error is that TL does not get informed by the browser when you click "Authorize". The "Cancel" button works.

Just give this 3 days and we will see what happens. I cannot make the Twitch website do stuff, so I also have to wait.

**Comment by Franiac** [comment] 2019-07-27 23:49
I got news. A Windows 10 Update messed up how the browser control in TL works. Basically I am using a native browser control fom Windows in order to show the Twitch authentication page. This native control now behaves weird and is basically not fixable.

I will implement CefSharp (an embedded Chrome browser) into TL. This has 2 minor downsides:

1. TL will grow in size significantly (~200mb) because Chrome is huge
2. TL will loose its 32 bit compatibility. But hey, it's not 1999 anymore, right?

I need a couple days to implement all this so be patient, please.

**Comment by Franiac** [comment] 2019-07-28 20:28
Fixed in upcoming 1.7.0

**Closed by Franiac** 2019-07-28 20:28 UTC
Labels: bug

**Comment by yztuar** [comment] 2019-07-30 13:18
When will 1.7.0 come?
