### ISSUE TITLE
Muted parts in playlist not downloadable / error in web player

### ISSUE THREAD

**Issue by pooiyx** [Franiac/TwitchLeecher#282] opened 2018-07-24 07:54 UTC
Within a few minutes of TwitchLeecher trying to download this vod (https://www.twitch.tv/videos/286102401), it gives a Status: Error with the following log: 
https://pastebin.com/xHKhvcbp

The video itself seems bugged on Twitch. When I try to watch it there, only the "red" parts play the video (muted of course), and the moment a non-red part tries to play, the screen goes black with the words "2000: Network error" on it. 
It seems like Twitch has butchered the vod by applying it's copyright mute filter to the video. 

Is there anything that can be done to retrieve the footage of this video? 
Thanks.

**Comment by Franiac** [comment] 2018-07-24 08:41
This seems to be a serious issue Twitch introduced a couple weeks ago. More and more videos show this behavior and more and more users contact me about it. The source of the problem is that the Twitch video playlist contains files marked as muted like so:

```
1.ts
2.ts
3-muted.ts
4-muted.ts
5.ts
6.ts
```
Some of the X-muted.ts files cannot be downloaded! This is NOT an issue of Twitch Leecher. As @pooiyx  stated, even the web player throws an error at those positions in the video. So Twitch screws up their videos apparently.

A temporary fix would be to just ignore the files that cannot be downloaded and are marked as muted. But this would result in videos that suddenly skips while watching.

We have 2 options in the end:

1. Do nothing and wait for Twitch to solve what they messed up
2. Skip the muted parts and therefor cut the downloaded video at those positions

I want to leave an additional note: In the end it's the streamers fault. By using non-free music in his stream he violates the copyright law resulting in muted videos. It is not TL's or Twitches  job to undo this misbehaviour. Twitch is just accommodating. They could very easily delete those streams instead of muting the parts. I receive many e-mails that indicate I am the one responsible and should fix it. This is simply wrong.

**Comment by igodorogea** [comment] 2018-09-17 10:31
@Franiac after a small investigation on this issue, I noticed that info in playlist is erroneous, some muted chunks are not marked as muted. That causes TL to fail.
Some data:
[In this playlist](https://fastly.vod.hls.ttvnw.net/2788702b01e5ccd4c16c_synderen_29572582256_916956554/chunked/index-muted-8AO4MDHSV3.m3u8), for example, on Line 1286 is a chunk [638.ts](https://fastly.vod.hls.ttvnw.net/2788702b01e5ccd4c16c_synderen_29572582256_916956554/chunked/638.ts) that returns 403, but it can download the [muted part 638-muted.ts](https://fastly.vod.hls.ttvnw.net/2788702b01e5ccd4c16c_synderen_29572582256_916956554/chunked/638-muted.ts).
Can another option be, to try to download the muted chunk when the original download fails?

**Comment by Franiac** [comment] 2018-09-17 16:00
@igodorogea So basically Twitch not only makes muted files not downloadable but also messes up the names of the muted and non-muted parts. It gets better and better.

What I am interested in right now is the following: Are those videos with a corrupt playlist playable in the web player? Because if not, I don't see any point in fixing those issues on my end. Don't get me wrong, but if Twitch itself cannot play back those videos, why should I put work into it.

Yesterday there popped up muted files in the playlist that are not downloadable...
Today we have non-muted parts that are actually muted...
I ask: What do we have tomorrow?

The thing is I would have already got onto the Twitch forums and told them how bad they are developing their stuff but I cannot do this because I don't know if they actually like what TL does or not 😅

**Comment by Franiac** [comment] 2018-09-22 22:44
I have a big problem with "do your best" software. They are all bad because the user does not know what the software does in a certain context. That is one of the worst behaviors a software can have. So my point stands: Twitch messes up their videos and I am not here to fix what they messed up because I cannot guarantee that the outcome is usable.

Under those circumstances I will close the issue now since I don't see me or us coming up with the "break through idea" how to deal with it other than erroring out like the web player also does.

**Closed by Franiac** 2018-09-22 22:44 UTC
Labels: discussion

**Comment by stenellad** [comment] 2018-09-27 15:47
I can tell you how I solved the problem myself: I went through to the twitch VOD's URL, looked for muted sections that didn't load, and manually recorded them. Then I went through and downloaded the sections of the VOD, using TL, with those parts removed. Then I manually concatenated them; when I upload the monstrosity to youtube, I'll have to include "<10 minute jump, sorry!" somewhere in the middle of the 10 hour vod.

The VOD I was downloading was the fifth of 9, and I didn't want to miss a giant multi-hour section in the middle over 10 minutes of deleted footage. The point of the anecdote is, at the moment, the solution to this problem is *exceedingly* tedious, and TL can probably do this task better and more efficiently than a human. Without this feature, people will still find a way, but damn, if there's a better way.
