### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by nord3838** [Franiac/TwitchLeecher#356] opened 2019-07-05 15:19 UTC
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 438434832
Selected Quality: 640x360@30fps
Download Url: https://www.twitch.tv/videos/438434832
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\ononoki\Downloads\20190613_438434832_Overwatch.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\ononoki\AppData\Local\Temp\TL_356e3c22-4bbb-4387-9759-12b0203fe050

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562411827%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A438434832%7D
Signature: 269d2fbe3da78ea7867d69b869a16ec34826e824
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\ononoki\AppData\Local\Temp\TL_356e3c22-4bbb-4387-9759-12b0203fe050'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\ononoki\AppData\Local\Temp\TL_356e3c22-4bbb-4387-9759-12b0203fe050'... done!

Download task ended with an error!

System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Net.WebException: リモート サーバーがエラーを返しました: (404) 見つかりません
   場所 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   場所 System.Net.WebClient.DownloadString(Uri address)
   場所 TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   場所 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   場所 System.Threading.Tasks.Task.Execute()
   --- 内部例外スタック トレースの終わり ---
---> (内部例外 #0) System.Net.WebException: リモート サーバーがエラーを返しました: (404) 見つかりません
   場所 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   場所 System.Net.WebClient.DownloadString(Uri address)
   場所 TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   場所 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   場所 System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment] 2019-07-05 18:37
Duplicate of #345

**Closed by Franiac** 2019-07-05 18:37 UTC
Labels: duplicate
