### ISSUE TITLE
Typo In Information About Twitch Icon (download sub-only VODs)

### ISSUE THREAD

**Issue by Muntafire** [Franiac/TwitchLeecher#64] opened 2016-10-24 00:25 UTC
"Authorize your Twitch account in order to **donwload** sub-only VODs"

The word shown is donwload instead of the correct spelling of download. I am referring to the Twitch icon in the upper-right corner.

**Comment by Franiac** [comment] 2016-10-26 17:21
Duplicate of #62

**Closed by Franiac** 2016-10-26 17:21 UTC
Labels: duplicate
