### ISSUE TITLE
Audio only not appearing for new videos

### ISSUE THREAD

**Issue by yohanosullivan** [Franiac/TwitchLeecher#160] opened 2017-07-01 22:54 UTC
Hello , huge fan of the program , thank you so much for it. Its made my commute much better! 

Recently the Audio only option stopped showing for the channel i watch -(Geekansundry) its a subscription only, not sure if that is relevant. Video download works fine and audio download works for old videos( a month or so back) but not new ones. 

kind regards, 

Mike

**Comment by Franiac** [comment] 2017-07-01 23:40
Duplicate of #149

**Closed by Franiac** 2017-07-01 23:40 UTC
