### ISSUE TITLE
Wont let me download 

### ISSUE THREAD

**Issue by ZxssT** [Franiac/TwitchLeecher#347] opened 2019-06-27 13:44 UTC
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 440934456
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/440934456
Crop Start: Yes (02:44:40)
Crop End: Yes (05:36:08)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Scholar\Downloads\20190618_440934456_Observation.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Scholar\AppData\Local\Temp\TL_f5c18ebd-3dee-4c34-add5-5c2d194dce57

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561714601%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A440934456%7D
Signature: 82772d71fd1cd2e6e76d07b8df32bbc3df18521e
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Scholar\AppData\Local\Temp\TL_f5c18ebd-3dee-4c34-add5-5c2d194dce57'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Scholar\AppData\Local\Temp\TL_f5c18ebd-3dee-4c34-add5-5c2d194dce57'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by garoto** [comment] 2019-06-27 17:19
Works for me:
```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 440934456
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/440934456
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: F:\Videos\downloading\BIG scare_20190618_JERICHO-v440934456.mp4
FFMPEG Path: C:\Apps\Diversos\TwitchLeecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\redacted\AppData\Local\Temp\TL_76f9ff0a-bdc3-4380-92ba-c4700e25789f

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561727872%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A440934456%7D
Signature: 4a47a2c59fcd601bb18ca770ba86c3311f63995f
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\redacted\AppData\Local\Temp\TL_76f9ff0a-bdc3-4380-92ba-c4700e25789f'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/1dc075a7bf9c1333a001_jericho_34581830848_1230029752/chunked/index-dvr.m3u8
https://vod-secure.twitch.tv/1dc075a7bf9c1333a001_jericho_34581830848_1230029752/720p60/index-dvr.m3u8
https://vod-secure.twitch.tv/1dc075a7bf9c1333a001_jericho_34581830848_1230029752/720p30/index-dvr.m3u8
https://vod-secure.twitch.tv/1dc075a7bf9c1333a001_jericho_34581830848_1230029752/480p30/index-dvr.m3u8
https://vod-secure.twitch.tv/1dc075a7bf9c1333a001_jericho_34581830848_1230029752/audio_only/index-dvr.m3u8
https://vod-secure.twitch.tv/1dc075a7bf9c1333a001_jericho_34581830848_1230029752/360p30/index-dvr.m3u8
https://vod-secure.twitch.tv/1dc075a7bf9c1333a001_jericho_34581830848_1230029752/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-secure.twitch.tv/1dc075a7bf9c1333a001_jericho_34581830848_1230029752/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2017

Starting parallel video chunk download
Number of video chunks to download: 2017
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\redacted\AppData\Local\Temp\TL_76f9ff0a-bdc3-4380-92ba-c4700e25789f'... done!

Download task was canceled!
```

**Comment by Franiac** [comment] 2019-07-02 13:42
Duplicate of #345

**Closed by Franiac** 2019-07-02 13:42 UTC
Labels: duplicate
