### ISSUE TITLE
2017 vod showing as live and therefore not downloadable

### ISSUE THREAD

**Issue by Zurlon** [Franiac/TwitchLeecher#734] opened 2022-03-08 23:41 UTC
VOD id = 152612160
This is what I see:
![image](https://user-images.githubusercontent.com/15965623/157344118-96b27d7c-da2b-490b-9708-893c5eb20a64.png)

(as you can see https://www.twitch.tv/videos/152612160 the vod is perfectly playable etc through browser)

Also the one thing I could think of was, is the vod being currently re-run on the channel? It is not at the time the screenshot was taken.

There's one other occurrence I found, exactly the same. Any ideas @Franiac?

edit: more than 1, found at least 4 with just a quick scan down a year's worth of vods

**Comment by Zurlon** [comment] 2022-03-08 23:43
Also the one thing I could think of was, is the vod being currently re-run on the channel? It is not at the time the screenshot was taken.

**Comment by Franiac** [comment] 2022-03-09 00:47
The thumbnail is currently the issue and I am aware of that. I needed a quick way to implement this, so if a stream comes up with this thumbnail, it gets marked as live. It looked consistent, but as it stands right now, it is not always the case. I'll have to look into it. I will close this one to not draw further attention to the live video download debate because I am really sick of it. So don't get me wrong, the issue is on my list!

**Closed by Franiac** 2022-03-09 00:47 UTC

**Comment by Zurlon** [comment] 2022-03-09 01:09
Sure thing, just to say your way of checking if a stream is live combined with some kind of basic check on how long ago the video was broadcast would work surely? Anyway thanks for looking into it.
