### ISSUE TITLE
The Remote Server Returned an Error: 410 Gone Wrong

### ISSUE THREAD

**Issue by vyperszn** [Franiac/TwitchLeecher#422] opened 2019-11-16 19:42 UTC
Why is still happening? This software was working fine yesterday!
![image](https://user-images.githubusercontent.com/57767222/68998368-5ea59480-087f-11ea-8c64-7a0ccf2263cf.png)

**Comment by Paticern** [comment] 2019-11-16 19:50
Duplicate of #419

**Closed** 2019-11-16 19:55 UTC
