### ISSUE TITLE
Error al descargar

### ISSUE THREAD

**Issue by TommyGines** [Franiac/TwitchLeecher#350] opened 2019-06-29 22:35 UTC
Hola tengo un error al querer descargar mi archivo, nunca me había pasado ¿Me podrian ayudar plis? ya intente desinstalado e instalando 

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 444788398
Selected Quality: 1280x720@60fps (Source)
Download Url: https://www.twitch.tv/videos/444788398
Crop Start: Yes (02:00:00)
Crop End: Yes (02:56:32)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\SPARTAN PC\Downloads\20190626_444788398_Fortnite.mp4
FFMPEG Path: C:\Program Files (x86)\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\SPARTAN PC\AppData\Local\Temp\TL_ffec735c-b0cd-4856-a989-d50b45dc47ea

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561919474%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A444788398%7D
Signature: 4869a4057b45de9953d56ab2034cb437c57d21cb
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\SPARTAN PC\AppData\Local\Temp\TL_ffec735c-b0cd-4856-a989-d50b45dc47ea'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\SPARTAN PC\AppData\Local\Temp\TL_ffec735c-b0cd-4856-a989-d50b45dc47ea'... done!

Download task ended with an error!

System.AggregateException: Se han producido uno o varios errores. ---> System.Net.WebException: Error en el servidor remoto: (404) No se encontró.
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   en System.Net.WebClient.DownloadString(Uri address)
   en TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   en TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   en System.Threading.Tasks.Task.Execute()
   --- Fin del seguimiento de la pila de la excepción interna ---
---> (Nº de excepción interna 0) System.Net.WebException: Error en el servidor remoto: (404) No se encontró.
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   en System.Net.WebClient.DownloadString(Uri address)
   en TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   en TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   en System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment] 2019-07-02 13:43
Duplicate of #345

**Closed by Franiac** 2019-07-02 13:43 UTC
Labels: duplicate
