### ISSUE TITLE
Audio sync issues

### ISSUE THREAD

**Issue by Valentin-Aslanyan** [Franiac/TwitchLeecher#96] opened 2017-01-30 11:27 UTC
Versions: 1.3.3 - 1.3.6
OS: Windows 10 64-bit
Example VOD: https://www.twitch.tv/videos/117288629

Firstly, may I just applaud the excellent project and keep up the good work!

However, every Windows version I've used (started with 1.3.3) has had problems with the audio track. I'm afraid I don't have the technical expertise to diagnose this in detail, but I have noted the following:

- Version 1.3.3 created a constant delay between video and audio iff the clip start time was set, and seemed to be ever so larger the longer the start time was, leading me to believe that this delay is proportional to the video run time (i.e. starting 3h into video it is longer than 1h).
- Fresh install of Version 1.3.6 created a complete mismatch in audio: Viewing the resulting video with the latest VLC was fine, but attempting to modify the video with any software, e.g. Avidemux, VDSC, Windows Movie Maker (embarrassing, but I was frustrated) caused a complete desync in audio
- I tried to investigate the above issue further, by attempting to extract and save the audio on its own. I did this using VLC's media extraction, with Avidemux's "save audio" and with ffmpeg -i file.mp4 file.mp3, the latter in both Windows 10 and Ubuntu. The mp3 files produced in this way all had different lengths to each other and the original video clip, e.g. 27.12s vs 27.16s video clip, meaning that the audio would be shorter by 4 seconds in the latter and therefore impossible to sync with the video.
- Finally, I checked the version of ffmpeg_64.exe in the Windows release and replaced it with the very latest similar binary available. I then downloaded an identical clip. Repeating the above mp3 extraction, the clip was again different from both the video and from the mp3 extracted previously! Most peculiar.

**Comment by Shilor37** [comment] 2017-01-31 05:46
I've also experienced de-sync in audio whilst editing in Adobe Premiere since version 1.3.4. In version 1.3.3 I didn't have any audio issues for the clips I use which were roughly 20 minutes in length. So I will be using the older version for the time being. I have also noticed in Premiere that the new clips vs the old clips, the frame rate differs from 30fps to 29.97fps. It's as if the video is now being processed differently than before. However even with a sequence matching that the audio de-sync will still occur. Just thought I'd add my 2 cents in hopes of future improvements to such an awesome program

**Comment by Valentin-Aslanyan** [comment] 2017-01-31 08:09
I agree - if version 1.3.3 still worked, everything would be fine, as I can adjust for the constant offset. The problem is that twitch changed their URL format or whatever, so it purely doesn't work now.

**Comment by Franiac** [comment] 2017-01-31 10:37
See Issues #72 and #79 

First things first: You talk a lot about VODs but do not provide a single url so I can possibly reproduce the issue. Please provide some examples.

You have to understand, that TL has nothing to do with how VODs are encoded or processed. All TL does is merging VOD parts together. This happens without re-encoding! If I did any processing on the VOD it would take hours after the download. So the video and audio streams are just copied by ffmpeg as they are (or as the streamer set up his encoder).

@Valentin-Aslanyan One good point you made by yourself: VLC plays back the VOD perfectly so the source material has to be correct somehow, right?

Premiere has a known bug where it is unable to process certain video files depending on the source material. It is also known that Adobe tells their customers to use Handbrake in order to fix the issue (which is a dick move in my opinion). They seem to give not many f**ks about their video processing product being unable to process some video formats.

So if a resulting VOD can be processed in certain video programs is heavily depending on the streamers' encoding settings. If the streamer messes up (using VBR for example), Premiere cannot process the VOD due to the official bug they probably won't ever fix. The same goes with the infamous 29.97fps. I do not know the background but many video processing tools interpret 29.97fps as 30fps and this way introduce A/D desync.

So again, TL uses ffmpeg to merge the VOD parts. You can see the command line arguments here at line 1093:

https://github.com/Franiac/TwitchLeecher/blob/master/TwitchLeecher/TwitchLeecher.Services/Services/TwitchService.cs

There is not much that I can change. Maybe a ffmpeg-pro could help but I am not one of them.

Conclusion: If a VOD works or not is not depending on the version of TL, because it is ffmpeg that does the job and I usually do not change anything in that regard. It is depending on the streamers' encoding settings. So one VOD may work and another won't. So far I only encountered problems whenever a streamer did not read the various how-to's on Twitch.tv on how to set up a stream.

**Comment by Valentin-Aslanyan** [comment] 2017-01-31 11:01
I had checked the other issues, but they were from version 1.3.3 which was working well.
Original post updated with an example (except for log, which would probably be fine, since there are no errors). I was not aware of a 29.97 FPS issue, but now that you mention it, this could be causing problems.  
What I find interesting is that, as I mention, extracting the audio with ffmpeg produces a different length section - since ffmpeg itself is being used to concatenate the segments and also that different versions of ffmpeg seemed to produce different results.
Meanwhile, I used ffmpeg and youtube-dl to download the entire VOD given in the example and the audio integrity seemed fine. 
Once again, the effort to run this project is very much appreciated and I can totally understand that it is out of your scope to somehow account for different encoding methods on the streamers' side or whatever.

**Comment by Franiac** [comment] 2017-01-31 11:05
I'll check that COD. What you probably could do is reviewing the command line arguments of the ffmpeg command in youtube-dl. I do not know that tool (only heard about the name). As you might have seen I introduced the "concat" argument lately in order to fix (LOOOL) A/V desync problems mentioned by user "Solar-Plexus". And apparently the changes helpt a lot of people. So I am very picky about removing a working bugfix again. First I really need to know exactly what is causing the problems and what a potentioal fix is.

**Comment by Valentin-Aslanyan** [comment] 2017-02-01 12:41
Some more thoughts on this issue:

- I completely agree with your statement that if it works perfectly in VLC, then it's correct fundamentally. However, I've noticed that, for VOD sections with a user-set start time that the first couple of seconds of video are blank or frozen in VLC. Probably this then propagates to any editing software.
- Could this be happening because of how twitch stores its VODs in sections? I for one would be happy if TL used the user set time to e.g. find the start/end of the nearest section if this improves fidelity. I believe this is a warning given on the now-unsupported livestreamer package.
- Regarding the 29.97 FPS: firstly, TL seems not to have sufficient precision and at the downloads screen quotes this as 30 FPS (is this stored as an int?). Secondly, I tried several streamers and this audio sync seems to be an error with ones using strictly 30 FPS also.

**Comment by Franiac** [comment] 2017-02-01 12:53
1. I noticed that hickup at the beginning of the playback, too. TL processes the playlist and throws away all sections below the start time threshold. If then the start time is within the first section (let's say 450ms) TL feeds ffmpeg with -ss 450 or whatever the argument was to set the start seeking time.

2. TL used to do that. But the problem is, sections are USUALLY 2s long, but that is not strictly defined and can grow up to 10s from what I have seen. And if your cropping times vary that much, I will probably get more issues about the "incorrect" cropping calculation.

3. ffmpeg throws all kinds of weird errors sometimes. But due to my lack of understanding video encoders, I cannot judge if those frames cause any problems.

4. The fps shown in TL has nothing to do with how it is processed. It is a rounded value for the UI, nothing more. This value is never being passed to ffmpeg or whatever processing within TL... it's just visual. Could you provide a VOD url that actually contains a 29.97fps stream? I could show the actual fps. Don't really know why I decided to round it in the first place...

**Comment by Valentin-Aslanyan** [comment] 2017-02-01 13:00
My example should be 29.97. 
If this was responsible for the problems, I was about to advise that at the very least TL could throw up a warning to inexperienced users. I am sure that most people came to it, like me, after googling "how to download from twitch" and finding that 5/6 of the suggestions in the top results don't work or have been discontinued.

**Comment by Franiac** [comment] 2017-02-01 13:06
Well, I do not like such "we actually don't know how to fix it"-solutions. I will investigate further when I have more time. It is difficult to get freetime for programming atm.
Should there really be a problem with 29.97fps, then the real fix for me would be to slap the streamers in the face who stream with this framerate. Kind of a "Switch to 30, idiots"-solution 😄 
Yeah, many of those other tools were programmed by hobby-developers who know what an integer is (don't want to be disrespectful, but you get what I mean). I the end it's serious business to keep up with all the changes and issues that come up when you publish such a tool.

**Comment by Valentin-Aslanyan** [comment] 2017-02-01 23:40
I totally understand that, as is typical for open source projects, you have a **thankless** task maintaining the project, when users will constantly complain about bugs. Well, a big thank you from me.

I believe I have stumbled on some very important evidence and possibly elucidated the problem, part of which does indeed lie with 29.97fps. My suggestion of a flag for inexperienced users was to do exactly as you suggested - they could at the very least pester their favourite streamer to switch to a more sensible frame rate.

Firstly, I downloaded an entire VOD, so that there could be no desync, at least from the start, and no blank section either. Explicitly ordering the video editor to work in 29.97fps and cutting out a section worked well, but again I got a sudden desync in the middle. This is the VOD ( https://www.twitch.tv/videos/118751680 ) and the desync happened for me at around 2:57:59, when the red countdown is at ~23s. It is a freeze of the video in VLC and VDSC - I am guessing a broken chunk? Probably nothing that TL can do about it, but if every VOD contains a few of those, maybe this could explain the eventual desync? Anyway, at least that can be reproduced and studied.

**Comment by Shilor37** [comment] 2017-02-04 15:09
@Franiac Apologies for not providing a link earlier. I Just did another test with this VOD https://www.twitch.tv/videos/116990011

When I download the VOD with Twitch Leecher 1.3.3 I have no audio de-sync issues in Adobe Premiere and the file is reported to be 30fps as expected. Everything is perfect.

When I download the same VOD with any other later version of Twitch Leecher I end up having de-sync issues in Adobe Premiere and the file is reported to be 29.97fps. The de-sync is easily noticeable at the end of the video when lip sync is out of time

I stream at 30fps and constant bitrate was set in OBS. I also tried re-encoding with handbrake but it made no difference.

I hope this is helpful in some way.

**Comment by Franiac** [comment] 2017-02-04 18:20
Ok guys, I am going to try to sum things up in order to structure this discussion a little bit:

In TL <=1.3.3 we had some really RARE issues with A/V desync ( #79 ) and a couple issues ( #58 ) were VODs failed the processing step and were shorter than the original.

In these older versions of TL, ffmpeg was set up like this:

`ffmpeg.exe -y -i [playlistFile] -analyzeduration [value] -probesize [value] -c:v copy -c:a copy -bsf:a aac_adtstoasc -ss [crop-start-value-if-set] -t [length-if-crop-end-set] [output-file]`

The important thing here is the [playlistFile]. That is the original m3u8 playlist file from twitch. This file contains not only the VOD parts but also information tags. One of those is the DISCONTINUITY flag that tells the encoder (in this case ffmpeg) that encoding settings were changed during video playback. Keep that in mind for a second!

In TL >= 1.3.4 I "fixed" #79 and #58 with the idea of GitHub user Solar-Plexus who recommended concatinating the VOD parts before the processing step like this:

`ffmpeg.exe -y -f concat -safe 0 -i [partsList] -analyzeduration [value] -probesize [value] -c:v copy -c:a copy -bsf:a aac_adtstoasc -ss [crop-start-value-if-set] -t [length-if-crop-end-set] [output-file]`

The important thing here is that [partsList] is only a list of the single files that are concatinated by ffmpeg before processing. This file does not conain any information regarding the original playlist (and this way also no DISCONTINUITY flags and so on).

My guess is that without the playlist information, ffmpeg just merges all the files with the encoder settings of the first one it finds while totally ignoring encoder/framerate/bitrate changes of the other parts. This way we probably end up with all these new A/V desync issues and weird framerate stuff in video programs.

No we have a big problem: I do not know how to combine the best of the two worlds together in order to fix ALL issues. Right now I definitely feel that I should rollback TL to the old ffmpeg command because we did not encounter that many issues compared to the new command. And it feels logical due to the fact that ffmpeg is not given the original VOD playlist with all those flags.

**Another thing regarding anyone using Adobe Premiere:**

If you have issues with VODs downloaded with TL in premiere that does not mean that TL is actually bugged. Premiere itself has confirmed bugs regarding twitch VODs (framerate and A/V desync issues). So I cannot give any credit to comments about Premiere either working or not because it does not tell me anything. Could be right , could be wrong. That is why I trust VLC, Sony Vegas, Sony Movie Studio, Hitfilm, Lightworks, Da Vinci and even Windows Movie Maker 10000 times more than Premiere.

**Any help/tests/input/expertise/suggestions/opinions regarding this issue are very welcome!**

**Comment by Valentin-Aslanyan** [comment] 2017-02-04 21:44
Am I right in thinking that the ffmpeg command line options used by TL are set at compile time? If so, could you provide some sort of checkbox for arguments 1/2 in for example the preferences tab for now?

**Comment by Franiac** [comment] 2017-02-04 22:00
That won't happen. From those 20000 a month downloading TL 3 or so know what and when to use this option... so no, I don't like this approach.

**Comment by Franiac** [comment] 2017-02-14 16:04
@Shilor37 After checking out your provided VOD I relized that the VOD is out of sync even on Twitch when you watch it in the browser. Thats the problem of the streamer not setting up hes delays correctly.

@Valentin-Aslanyan Your video https://www.twitch.tv/videos/117288629 is completely broken somehow. FFMPEG goes crazy on that one and downloading it even with TL 1.3.6 I do not get a longer VOD than 10 minutes on the hard drive because ffmpeg messes it up. So this VOD seems to be broken anyway and making assumtions how A/V sync may be affected by TL based on this VOD would be not very intelligent.

Another thing I want to add: I have played around with many many channels now and I cannot reproduce a single problem with TL 1.3.6 on all those. The only VODs all that happens are from "OddishPlaysGames". Furthermore, the emails hitting my inbox regarding A/V desync and issues with shorter VODs on the harddrive went down to exactly 0.

I really need proof that this whole issue is not only caused by very few channels. I have a good feeling about the changes I made in TL 1.3.4 if I take all the feedback into account that hits my inbox (and that is way more than here on GitHub). I will keep this issue open for now but I will only investigate further when there is more material to work with than from a single channel. I'll keep my eyes open, too.

**Comment by Franiac** [comment] 2017-02-14 16:16
Ok, after investigating issue #103 I realized that there is a small hickup whenever a new VOD part is loaded. Since TL merges all those together, those hickups sum up and make the VOD actually longer. Based on this I cannot keep the way ffmpeg is set up since TL 1.3.4 (what a change of things again). I will fall back to the old way without concatenating the VOD parts before processing.

This all is really fucked up to say the least and I am quite unhappy that I cannot provide a stable solution for all users. Not my style of implementing things, really... but what options do I have. None at the moment :(

**Comment by Valentin-Aslanyan** [comment] 2017-02-14 18:17
@Franiac Not sure how to understand your last two messages, because first you're saying that it's a particular broken video on one particular streamer and then that there is an overall bug for all or TL.

I was able to download the entire video mentioned, not sure why you only got the first 10 minutes. Anyway, to prove that the problem persists on other channels, consider the streamer TrumpSC, who regularly gets 20k+ concurrent viewers (so a pretty serious streamer). Picking a recent video at random, say: https://www.twitch.tv/videos/120958751 and downloading a section from 04:00:00 to 04:20:00 I get the exact previously reported problem. It plays OK-ish in VLC, but any attempt to edit it produces desyncs an extracting the audio produces a 2 second shorter clip than the video.

**Comment by Franiac** [comment] 2017-02-14 19:03
Ok first of: I just released TL 1.3.7 which rolled back the concat-thing with ffmpeg. I realized that this change introduced some major stuttering between the VOD parts and even lengthened the whole VOD in the end due to added frames. See issue #103 for that. I did that because of #79 believing Solar-Plexus found a solution which turned out to be not the case. It was my mistake to not test this better because of my lack of freetime. So basically TL 1.3.7 is ffmpeg-wise on the same state like TL 1.3.3

Now to the editing part. I am dealing with a couple issues in parallel so I got a little bit confused and thought you also had problems with A/V sync in VLC.

I just tried downloading parts of all VODs you provided me with TL 1.3.7:

https://www.twitch.tv/videos/120958751 (04:00:00 to 04:20:00)
https://www.twitch.tv/videos/118751680 (03:00.00 to 03:10:00)
https://www.twitch.tv/videos/117288629 (02:45:00 to 02:57:00)

Then I imported all these videos into Sony Vegas Pro letting the software set the project defaults to the source material (doing it for every different video). None of the videos where out of sync, none had hickups.

Then I imported all videos into Hitfilm Express. No problems at all, no hickups, no A/V desync.

Then I imported all videos into Davinci Resolve 12.5 (free edition). No problems at all, no hickups, no A/V desync.

VLC plays all the videos back perfectly (not only "ok-ish"). Even if I render those videos back to mp4 or avi with any of those programs they're still in sync.

After all this hassle I have no indicator that either TL or ffmpeg is doing anything wrong. I cannot take over support for any external software you are using. Fact is, 3 professional video editing tools handle it correctly and due to my long experience in video editing (I am a YouTuber, too) Vegas is the only video software I honestly trust.

After my mistake with #79 I will not make any quick changes to TL/ffmpeg until there is proof that ffmpeg is the source of the problem and a possible solution was properly tested. On my side I have nothing more to investigate. All I can see here is that it all works now.

**Comment by Shilor37** [comment] 2017-02-15 04:19
@Franiac Hey dude, Yes there is a tiny delay in the VOD. Part of it might be a bug with the Twitch HTML 5 player as I have downloaded that VOD with TL 1.3.3 and edited it in Adobe Premiere without any kind of de-sync issues. The final result is better on YouTube as seen here https://www.youtube.com/watch?v=uOdIZfMLMno. Also that isn't the kind of audio de-sync I am referring to with the issue. The de-sync I have been experiencing is forever increasing gradually not like a constant delay which you've noticed in the VOD. In longer videos that are brought into Premiere eventually will have words from other sentences be heard when they are not spoken etc.

I have just tested the newest update TL 1.3.7 and I no longer experience the issue originally mentioned. It appears I can edit just as I did with 1.3.3 with no audio de-sync. This is amazing!

**Comment by Franiac** [comment] 2017-02-15 10:26
@Shilor37 That makes sense due to added frames when concatinating the VOD parts with ffmpeg. See #103 

It added frames on the video stream while leaving the audio stream alone. Logically that introduced more A/V desync over time.

I expected this to be fixed with 1.3.7. And it also tells me that if Premiere is capable of handling VODs downloaded with TL, we must be doing something right here.

I am curious if @Valentin-Aslanyan is now too capable of editing VODs with 1.3.7. I honestly hope so but if not, all signs point to an issue on the client machine rather than TL/ffmpeg.

**Comment by Valentin-Aslanyan** [comment] 2017-02-19 11:45
Seems to work much better with editing software now!

**Comment by Franiac** [comment] 2017-02-19 15:03
@Valentin-Aslanyan  That's the answer I was hoping for... Closed!

**Closed by Franiac** 2017-02-19 15:03 UTC
Labels: waiting for response

**Comment by kristerols** [comment] 2017-10-12 17:19
I came over this thread also having audio sync issues with Twitch VODs. I have the same problem as described earlier, about the difference fps on VODs(60fps and 59fps instead of 30 and 29) where the 60fps play fine, but the 59 fps goes more and more out of sync throughout the timeline in Premiere Pro(Still plays fine in VLC). 

BUT, I don't use TL since I'm an editor on the Twitch channel I download from. I can highlight the section from the Twitch dashboard and download from the browser. So I can confirm that the Premiere Pro issue with 59fps or 29fps VODs where the video plays fine in VLC, but goes out of sync in Premiere Pro has nothing to do with TL ;)

Gonna try another edit software and also transcode the file with Adobe Prelude.

Cheers! :)
