### ISSUE TITLE
Audio and Video Desync

### ISSUE THREAD

**Issue by Plugra** [Franiac/TwitchLeecher#78] opened 2016-12-20 16:32 UTC
Hi. When I download a video in its entirety it turns out fine. But when I use the cropping feature to download portions of a video the audio lags about 3-4 seconds behind the video.

**Comment by Franiac** [comment] 2016-12-20 18:21
https://github.com/Franiac/TwitchLeecher/blob/master/README.md#support--issues

**Comment by Plugra** [comment] 2016-12-21 22:51
I'm sorry, I didn't see that.

1) I'm using version 1.3.3.
2) This is affecting all videos I download, but the latest one I downloaded was:
https://www.twitch.tv/werster/v/105107060
3) I'm using Windows 7 64-bit Home.
4) On the download page there is an option to select Start and End times for downloading a portion of a video instead of the entire thing. When I download an entire video (not using the cropping feature) it turns out fine. But when I enter Start and End times the audio and video of the downloaded file desync. The sound lags behind the video by about 3-4 seconds. This affects all videos I download using the cropping feature, regardless of channel or duration of the video.
5) http://pastebin.com/azzP7MNN

**Comment by kartakur** [comment] 2016-12-29 11:58
I have same problem

- Using 1.3.3

- Windows 10 64-bit

**Comment by Franiac** [comment] 2017-01-01 20:33
Issue #79 is a very interesting approach. I will check it and there is a high possibility that it also solves this one.

**Comment by Franiac** [comment] 2017-01-12 23:07
I cannot reproduce the issue on my system (TL 1.3.3, Win 10 64 Bit). It does not matter how I crop the VOD, audio is always in sync.
I hope you are not trying to edit the VOD in Adobe Premiere, because that crap has indeed issues with A/V sync that are not related to TL, though.

**Comment by Franiac** [comment] 2017-01-14 23:22
So after intensive testing I still cannot reproduce this issue on various Windows systems. The next version of TL will introduce a major enhancement regarding the ffmpeg muxing process. I close this issue, it may be reopened when TL 1.3.4 does not change anything.

**Closed by Franiac** 2017-01-14 23:22 UTC
