### ISSUE TITLE
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue

### ISSUE THREAD

**Issue by mgrandi** [Franiac/TwitchLeecher#679] opened 2022-01-30 02:00 UTC
This error seems to be intermittent, It failed a few videos in a row  and then when I checked back later and hit 'retry', they seemed to download fine

other videos that hit this:

https://www.twitch.tv/videos/1226731700
https://www.twitch.tv/videos/1227627033
https://www.twitch.tv/videos/1228620549
https://www.twitch.tv/videos/1223949606 (log provided below)

```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1223949606
Selected Quality: 480p (852x480)
Download Url: https://www.twitch.tv/videos/1223949606
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: Yes
Output File: D:\TwitchLeecherOutput\20211204_095800_nukkular_reaction_1223949606_[Randomizer] NEW !Song Locations 5 Dungeonsanity  ⋅  !Madrinas_852x480_000000_071930_v2.ts
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: D:\TwitchLeecherTemp\dd29a9225a4a49118b196bf459e6094c

Retrieving VOD access information...

Starting temporary download folder cleanup!
Deleting directory 'D:\TwitchLeecherTemp\dd29a9225a4a49118b196bf459e6094c'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at TwitchLeecher.Services.Services.ApiService.GetVodAuthInfo(String id)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at TwitchLeecher.Services.Services.ApiService.GetVodAuthInfo(String id)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by Franiac** [comment] 2022-01-30 12:28
I cannot reproduce the issue unfortunately. The downloads work perfectly on my end. I try to implement some more checks into TL in order to output more meaningful error messages. As far as I can tell, Twitch did not grant you an access token for the video on the first try.

Can you tell me if you have sub-only support enabled or not?

**Comment by mgrandi** [comment] 2022-01-31 04:11
i didn't have that enabled, however these videos shouldn't be sub only , and they worked after i retried after the above error

**Comment by Franiac** [comment] 2022-01-31 10:58
No the videos are not, but it is necessary to know if you have sub-only enabled or not because the access token gets created differently. I'll add that to the download log.

**Comment by Franiac** [comment] 2022-01-31 12:24
All in all this seems like a hickup on Twitches end. I cannot create any scenario where the access token value would be emtpy. I am closing this for now but if this happens again, please let me know.

**Closed by Franiac** 2022-01-31 12:24 UTC
Labels: cannot reproduce
