### ISSUE TITLE
Log-in or Sign up won't work

### ISSUE THREAD

**Issue by InaneInaccompli** [Franiac/TwitchLeecher#800] opened 2022-09-24 07:21 UTC
![image](https://user-images.githubusercontent.com/92868301/192085527-34bb6e4c-0e1c-4c1c-b63d-3ae927619db9.png)

When I try to create an account, an error is displayed, whereas when I do it on navigator, this problem doesn't happen. And even when I don't create my account, I cannot connect

Did I do something wrong ? I'm on Windows

**Comment by andrhp87** [comment] 2022-09-24 15:44
I am also unable to log in via my existing account. I am on Windows 11.
![error_login](https://user-images.githubusercontent.com/15995283/192106819-67970c69-57e3-46d2-bbc0-d89848fe18aa.jpg)

**Comment by Dochigi** [comment] 2022-09-24 16:17
I have similar symptoms in the 'Whale' browser, so I'm working on it. The problem analyzed there is this

"Twitch login, which was working normally, has been failing due to a change in the site since yesterday

The cause is caused by an error in the browser when branching UA from the server, and the team is developing and implementing measures to take UA action online for source response."

**Comment by Franiac** [comment] 2022-09-24 18:36
@Dochigi Can you elaborate more on

> when branching UA from the server, and the team is developing and implementing measures to take UA action online for source response

I don't quite get what you are trying to say.

My wild guess is that Twitch tries to deny running their authentication form anywhere else than twitch.tv

That would mean we need to implement a proper OAuth login cycle via the browser instead of an integrated browser in TL.

**Comment by Franiac** [comment] 2022-09-24 18:48
I tried to step through the process with the integrated Chrome DevTools in TL. The JavaScript console throws this error when the authentication form is loaded:

`[GraphQL] One or more GraphQL errors were detected on request 01GDRCQA51YYAPNPEGZKDM0SC1. ConnectAdIdentityMutation: failed integrity check`

After providing the username and the password and clicking on 'Log In' the console provides another error, probably a followup to the first one:

`POST https://passport.twitch.tv/integrity 400 (Bad Request)`

This is interesting. The integrated browsers in applications like TL could be kicked out of the Authentication and GraphQL API. I do not know yet how to deal with this. Other downloaders do not work with authentication and only use the public GraphQL API with the Twitch website Client-ID (which is illegal but somewhat tolerated). That's why there are tools that work.

**Comment by MproductionMaddue** [comment] 2022-09-24 18:59
I have the same problem. Thank you for working on it Franiac!

**Comment by kouccarter** [comment] 2022-09-24 20:35
Hello, i have the same problem. Good luck to solve ! O:)

**Comment by Franiac** [comment] 2022-09-24 21:42
LISTEN! We do not need any more `I have the same problem` posts. They do not help in any way to solve the issue.

**Comment by jin0616** [comment] 2022-09-24 23:34
I am not sure if this is a helpful information that you can work with but I also had an issue with the login in the twitch leecher and I thought I forgot my password so reset my password then I found out that some users getting same error messages when they are trying to login in different browser other than Firefox (excluding private mode and have to disable all the extensions) and Edge. That issue has been happening for last few days but twitch hasn't resolved the issue yet.

**Comment by akosirmpr** [comment] 2022-09-25 01:40
> LISTEN! We do not need any more `I have the same problem` posts. They do not help in any way to solve the issue.
> 
> Please keep it clean and only post stuff that might actually help.

Hello Sir/Maam i dont know if this helps but "Your tool is cool, it's free and helps me a lot to clip videos from Twitch, so THANK YOU, i hope everything will be okay soon"

**Comment by eraymitrani** [comment] 2022-09-25 03:40
What if you gave an option for people just paste their oauth token instead of authenticating within the app?

**Comment by kouccarter** [comment] 2022-09-25 11:00
> I am not sure if this is a helpful information that you can work with but I also had an issue with the login in the twitch leecher and I thought I forgot my password so reset my password then I found out that some users getting same error messages when they are trying to login in different browser other than Firefox (excluding private mode and have to disable all the extensions) and Edge. That issue has been happening for last few days but twitch hasn't resolved the issue yet. UPDATE: now there are other users who is still having same issues even when they try to use the above workaround so it i think its hard to figure out what the cause is.

Well "if only 1 human on planet has this issue = problem is between chair and computer" . But "if the same problem has many people = issue is probably in the software." Well, i think it is important to know. But, maybe i am wrong.

**Comment by Dochigi** [comment] 2022-09-25 22:58
I'm not good at English, so I used Google Translate.

Perhaps what they are trying to say is that there is a problem when using the User-Agent to check the environment of the device.

**Comment by Franiac** [comment] 2022-09-26 11:38
> What if you gave an option for people just paste their oauth token instead of authenticating within the app?

Because 98% of TL users don't even know what an authentication token is. You are not thinking for "Average Joe".

Other than that it would make for a really shitty user experience if you have to copy your token manually from browser DevTools or whatnot. Again, stuff "Average Joe" should not need to know about.

**Comment by Franiac** [comment] 2022-09-26 12:05
So here's what's going to happen:

* I will try to implement the proper OAuth flow
* Clicking `Connect` in TL will bring up the Twitch authentication form in the standard browser
* TL installer will register a custom url scheme `tleecher://` in the Windows registry
* I will have to change the redirect url fpr TL on Twitch from `www.tl.com` to `tleecher://`. This will enable the standard browser to open up TL with the returned authentication token and so on.
* Changing the redirect url on Tiwtch will render every single TL installation <= 2.0.7 on the planet unusable. But this is not really an issue since it does not work anyway, right?

**Comment by lvl99juls** [comment] 2022-09-27 05:54
When will be the app get fix @Franiac ?

**Comment by AncientBread** [comment] 2022-09-27 06:02
> So here's what's going to happen:
> 
> * I will try to implement the proper OAuth flow
> * Clicking `Connect` in TL will bring up the Twitch authentication form in the standard browser
> * TL installer will register a custom url scheme `tleecher://` in the Windows registry
> * I will have to change the redirect url fpr TL on Twitch from `www.tl.com` to `tleecher://`. This will enable the standard browser to open up TL with the returned authentication token and so on.
> * Changing the redirect url on Tiwtch will render every single TL installation <= 2.0.7 on the planet unusable. But this is not really an issue since it does not work anyway, right?

I know there is a current workaround on browsers by disabling (browser.js) allowing you to sign in to twitch, then you can re-enable it after. May be able to use this as a quick fix?

Note: I know nothing about what I'm talking about.

**Comment by Franiac** [comment] 2022-09-28 15:46
Btw. the fix will happen as soon as I am over the virus... It's battling me pretty hard right now.

**Comment by MPeti1** [comment] 2022-09-28 17:28
It might be related to this issue, but it seems loading a list of VODs for channels does not work anymore.
If it helps, last time it worked as usual was around 09.27. 11:00 (UTC), that is when I last downloaded a VOD. The first time I noticed this problem was today, around 20 minutes ago.

One of the symptoms is that in the search menu, the name of existing (and previously used) channel names are now red, as if they wouldn't exist, but thats probably just because of a general error.
An other symptom is that on restarting TL, a message is shown that an unexpected error occurred, and that a log file was saved. Contents of it are below:
```
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.ApiService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.ApiService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.ApiService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.ApiService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

> Btw. the fix will happen as soon as I am over the virus... It's battling me pretty hard right now.

I hope you will get better soon! Not just because of TL, but otherwise too.

**Comment by MPeti1** [comment] 2022-09-28 17:32
Also, you may want to change the issue title and pin it so others don't open duplicates.
This also might be an entirely different problem so opening a single separate issue for this error might be useful.

**Comment by NicoleKCat** [comment] 2022-09-28 17:38
> It might be related to this issue, but it seems loading a list of VODs for channels does not work anymore. If it helps, last time it worked as usual was around 09.27. 11:00 (UTC), that is when I last downloaded a VOD. The first time I noticed this problem was today, around 20 minutes ago.

As an aside, you're still able to pull vods via search by url or id, you're just not able to parse a vod list via a specific channel name as something in the search request itself is throwing an error, so at least with this you can still use the main feature of the program. 

With this error I'm still able to login and log out freely without any auth issues, without any investigation it's hard to say if they're related.

**Comment by MPeti1** [comment] 2022-09-28 17:54
> With this error I'm still able to login and log out freely without any auth issues, without any investigation it's hard to say if they're related.

So the primary error of this issue does not happen for everyone, right?

I can confirm that search by the VOD URL (e.g. `https://www.twitch.tv/videos/1602585936`) works, but for me the download starts too:

![image](https://user-images.githubusercontent.com/9215491/192854111-5bd36a52-aca6-4124-baab-74e0b7c08d82.png)

It's coming with the usual 150-160 Mbps speed.

Search by ID (e.g. `1602585936`) works too.

**Comment by MPeti1** [comment] 2022-09-28 17:58
Oh and this is with version 2.0.4.
Just noticed there are new versions. TL didn't let me know.

Side question: 2.0.5 brought in reusing TL instances. Is it still possible to open multiple seperate instances, though? (without closing the right handles of the process)

**Comment by Drolnevar** [comment] 2022-09-28 18:14
I am on version 2.0.5 and can confirm search AND download by ID or URL do still work. The downloads start and complete without issue. Search by username does not work however.
As for logging in, I assume we are talking about the sub only download function? I seem to still be logged in as the button is green but I am currently not subscribed to any channel that has sub only downloads activated so I can not test if those still work and I'm reluctant to log out (or change anything really) to test if I can log back in.

**Comment by MPeti1** [comment] 2022-09-28 18:28
> As for logging in, I assume we are talking about the sub only download function? I seem to still be logged in as the button is green but I am currently not subscribed to any channel that has sub only downloads activated so I can not test if those still work and I'm reluctant to log out (or change anything really) to test if I can log back in.

Log in has sadly become a requirement recently, for all 3rd party clients for Twitch services.
If you log out, you'll have to log in to be able to do anything.

**Comment by NicoleKCat** [comment] 2022-09-28 18:39
This seems to be an issue with the twitch API, it's affecting many different services.
https://github.com/streamlink/streamlink-twitch-gui/issues/910
https://github.com/twitchdev/issues/issues/664

Appears to be beyond the scope of this project's control.

**Comment by Drolnevar** [comment] 2022-09-28 19:51
Search by user is working again in 2.0.5

**Comment by MPeti1** [comment] 2022-09-28 19:52
Not yet in 2.0.4. But possibly it is just random.

**Comment by MPeti1** [comment] 2022-09-28 19:53
Well, now it's working for me too, but not always. Probably it'll be okay.

**Comment by palex00** [comment] 2022-09-29 19:36
I still cannot log in. I am using this version for the first time.

**Comment by carlop3333** [comment] 2022-09-30 13:20
> This seems to be an issue with the twitch API, it's affecting many different services. [streamlink/streamlink-twitch-gui#910](https://github.com/streamlink/streamlink-twitch-gui/issues/910) [twitchdev/issues#664](https://github.com/twitchdev/issues/issues/664)
> 
> Appears to be beyond the scope of this project's control.

It seems to be the browser restriction they put a week ago, they aclare it in they [twitter support](https://twitter.com/TwitchSupport/status/1575267327163207680?cxt=HHwWgMC83bbSvNwrAAAA)

**Comment by Franiac** [comment] 2022-09-30 13:41
> It seems to be the browser (engine) restriction they put a week ago, they aclare it in they [twitter support](https://twitter.com/TwitchSupport/status/1575267327163207680?cxt=HHwWgMC83bbSvNwrAAAA)

They actually say jack shit. Those idiots always change things first and then post on Twitter about it telling people they have to wait even pnger until there's an explanation as to why their software doesn't work for 2 weeks. Twitch Devs suck, they are so bad it's amazing.

And the Chrome/Firefox/Edge thing... TL uses CefSharp like millions of tools in the world. And CefSharp is based on the Chromium Engine. So if Chome works but Chromium-based browsers don't I fucking quit.

I am tired of running behind these idiots and picking up the garbage they produce.

**Comment by carlop3333** [comment] 2022-09-30 13:43
> > It seems to be the browser (engine) restriction they put a week ago, they aclare it in they [twitter support](https://twitter.com/TwitchSupport/status/1575267327163207680?cxt=HHwWgMC83bbSvNwrAAAA)
> 
> They actually say jack shit. Those idiots always change things first and then post on Twitter about it telling people they have to wait even longer until there's an explanation as to why their software doesn't work for 2 weeks. Twitch Devs suck, they are so bad it's amazing.
> 
> And the Chrome/Firefox/Edge thing... TL uses CefSharp like millions of tools in the world. And CefSharp is based on the Chromium Engine. So if Chome works but Chromium-based browsers don't I fucking quit.
> 
> I am tired of running behind these idiots and picking up the garbage they produce.

Yeah, opera is chromium based, and what do you think what happend? Oh the restrictions... they fixed it 3 days later...

**Comment by spli7er** [comment] 2022-09-30 16:55
is there a fix for the log in/sign up issue?

**Comment by carlop3333** [comment] 2022-09-30 18:43
> is there a fix for the log in/sign up issue?

Yes, still its not applied (op is busy so only way is a pr and i don't know much of c# only java)

**Comment by Franiac** [comment] 2022-10-01 14:45
So... I have bad news... and some other news.

I started to implement the state of the art OAuth 2.0 authentication workflow for TL via the standard browser and so on. As we discussed I need to change the redirect URL from `http://www.tl.com` to `twitchleecher:///` in order to be able to react to a successful authentication and send the authentication token back to the running TL application via custom url schemes.

I was nearly done when I finally connected to my Twitch Developer account in oder to see if I can add or change the above mentioned redirect URL. I filled the textbox and a nice heartwarming error message was presented to me:

`Redirect URL's have to be https://...`

So what this basically means is that it is not possible to receive an authentication token from Twitch outside of the browser because the system cannot react or interfere with `https://` requests. Or said differently: Because Twitch doesn't allow `twitchleecher:///` to be a thing, the browser cannot "call" Twitch Leecher and tell it "hey, here's something for you".

Short statement as to why other tools still work: Because they illegaly use the public GraphQL API the Twitch.tv website also uses. Why do I not want that? Because illegal, duh.... and because it changes without announcements since you shouldn't be using it anyways. And I am already playing enough cat and mouse with Twitch only using the official parts.


Now what? I don't fucking know... all I know right now is the following:

The decision to let Twitch Leecher go has been in my mind since my daughter was born in 2020. As you all can see, there are big and very important enhancement issues laying around since 2016 (#46 anyone???) and I just cannot find the time to implement them. The time where I could randomly program 5, 6, 7 hours at night without anybody caring are long over. Maybe the time has come to let someone else play the stupid Twitch game. TL has been around since 2015 (!) and Twitch itself has degraded in every regard that it is absolutely artrocious to implement anything around that pile of crap as a software developer with any sense of good software engineering. I am not really sure right now what to do... but for now I cannot do anything and I will let you know what happens to TL when I know, what to do with it.

I hope this does not break too many hearts. There are alternatives out there now compared to 2015... but... I think the only one with 7 years of solid support and uptime... is named `Twitch Leecher`

**Comment by NingunoNoone** [comment] 2022-10-01 23:23
> So... I have bad news... and some other news.
> 
> I started to implement the state of the art OAuth 2.0 authentication workflow for TL via the standard browser and so on. As we discussed I need to change the redirect URL from `http://www.tl.com` to `twitchleecher:///` in order to be able to react to a successful authentication and send the authentication token back to the running TL application via custom url schemes.
> 
> I was nearly done when I finally connected to my Twitch Developer account in oder to see if I can add or change the above mentioned redirect URL. I filled the textbox and a nice heartwarming error message was presented to me:
> 
> `Redirect URL's have to be https://...`
> 
> So what this basically means is that it is not possible to receive an authentication token from Twitch outside of the browser because the system cannot react or interfere with `https://` requests. Or said differently: Because Twitch doesn't allow `twitchleecher:///` to be a thing, the browser cannot "call" Twitch Leecher and tell it "hey, here's something for you".
> 
> Short statement as to why other tools still work: Because they illegaly use the public GraphQL API the Twitch.tv website also uses. Why do I not want that? Because illegal, duh.... and because it changes without announcements since you shouldn't be using it anyways. And I am already playing enough cat and mouse with Twitch only using the official parts.
> 
> Now what? I don't fucking know... all I know right now is the following:
> 
> The decision to let Twitch Leecher go has been in my mind since my daughter was born in 2020. As you all can see, there are big and very important enhancement issues laying around since 2016 (#46 anyone???) and I just cannot find the time to implement them. The time where I could randomly program 5, 6, 7 hours at night without anybody caring are long over. Maybe the time has come to let someone else play the stupid Twitch game. TL has been around since 2015 (!) and Twitch itself has degraded in every regard that it is absolutely artrocious to implement anything around that pile of crap as a software developer with any sense of good software engineering. I am not really sure right now what to do... but for now I cannot do anything and I will let you know what happens to TL when I know, what to do with it.
> 
> I hope this does not break too many hearts. There are alternatives out there now compared to 2015... but... I think the only one with 7 years of solid support and uptime... is named `Twitch Leecher`

I have been using the program for a long time. Thanks to you, I have enabled many people to watch videos quickly. Every year (lol) I downloaded the videos of the world championship through your program. Currently the program is not working, and I am still waiting for your program to be fixed, although there are many alternative programs as you said. I know, there are many alternatives. But I don't plan to use them at this stage. Perhaps there are many people who are as emotionally attached to your program as I am. Perhaps other alternative programs do not appeal to us. I don't know this. Maybe we will wait until TL works stable. Maybe you'll say, "Enough is enough, that's it". We will also start looking at alternative programs. I've never been a member here before. I wanted to write a few words. I wanted to thank you for wasting your precious time for me and many others like me. Thank you so much.

**Comment by DetectiveMyst** [comment] 2022-10-02 06:08
And here I was thinkin it was related to havin authy lock on my account

**Comment by spli7er** [comment] 2022-10-02 08:38
If anyone is looking for any alternatives, ive recently found one called twitch recover( https://github.com/TwitchRecover/TwitchRecover ). works great.

**Comment by Franiac** [comment] 2022-10-02 11:42
#803

**Closed by Franiac** 2022-10-02 11:42 UTC

**Comment by hungarywhite** [comment] 2022-10-02 17:55
The client is not connected! Correct name, correct password! "Something went wrong" error message! I'm helpless! Somebody help me! win 11 pro! leacher version: 2.0.7

**Comment by Shark-93** [comment] 2022-11-04 19:38
@hungarywhite if you manage to get to your hands on your own [user OAuth access_token](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#authorization-code-grant-flow), you just need to put it in `C:\Users\%username%\AppData\Roaming\Twitch Leecher\runtime.xml`, and when you launch the app you should be logged in ;)
```xml
<RuntimeData Version="2.0.7">
  <Authentication>
    <AccessToken> !!! token code goes here !!! </AccessToken>
  </Authentication>
  [...]
</RuntimeData>
```

**Comment by aniv1re** [comment] 2022-11-08 00:04
@Shark-93 I have inserted an OAuth access token as you have shown and am getting this error: `Twitch could not validate the saved access token. Try to log in again!` Maybe I'm doing something wrong, or is there something I need to know?

**Comment by Shark-93** [comment] 2022-11-08 09:05
I don't actually know, because in my case I was already logged in through the app before.
Copying %appdata% folder from my PC to another, would log me in on the new machine.

> 98% of TL users don't even know what an authentication token is.
You are not thinking for "Average Joe"

Perhaps Franiac could point you in the right direction, because as things stand, "Average Joe" can't even download the app :P actually, I remembered/noticed that _you need to authorize the app._

So I've poked around the code and this should be the exact URL that is used to create the access_token: [id.twitch.tv/oauth2/authorize](https://id.twitch.tv/oauth2/authorize?client_id=37v97169hnj8kaoq8fs3hzz8v6jezdj&redirect_uri=http://www.tl.com&response_type=token&scope=user:read:subscriptions&force_verify=true). I'm not sure how to get the access_token json afterwards though, so if you could explain how you do it for posterity we would be grateful.
