### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by nightwinggrayson** [Franiac/TwitchLeecher#352] opened 2019-07-01 13:32 UTC
When I tried to start download a video, I got an immediate error while initializing
Here is the download log:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 446397046
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/446397046
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\jerem\Downloads\20190701_446397046_Just Chatting.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\jerem\AppData\Local\Temp\TL_cea1a2f9-1fcb-4dfe-a0eb-2126ae16efa4

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562058779%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A446397046%7D
Signature: fd60d1a0b8705fb26fcfe467c7562d898a0a6bb8
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\jerem\AppData\Local\Temp\TL_cea1a2f9-1fcb-4dfe-a0eb-2126ae16efa4'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\jerem\AppData\Local\Temp\TL_cea1a2f9-1fcb-4dfe-a0eb-2126ae16efa4'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

So can someone help me? Thanks!

**Comment by gorogun** [comment] 2019-07-02 02:38
I have the same issue, I guess it was since past thuesday or friday. Is there a solution yet?

**Comment by Franiac** [comment] 2019-07-02 13:43
Duplicate of #345

**Closed by Franiac** 2019-07-02 13:43 UTC
Labels: duplicate
