### ISSUE TITLE
Download Error is still happening

### ISSUE THREAD

**Issue by Zar300** [Franiac/TwitchLeecher#354] opened 2019-07-03 03:43 UTC
Literally every VOD I have put in has given me this

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 447362459
Selected Quality: 1280x720@30fps (Source)
Download Url: https://www.twitch.tv/videos/447362459
Crop Start: Yes (00:01:00)
Crop End: Yes (00:01:30)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\zar\Downloads\20190702_447362459_Overwatch.mp4
FFMPEG Path: C:\Users\zar\Pictures\1\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\zar\AppData\Local\Temp\TL_97ea16de-afae-4bbb-af2e-9117f497c65f

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562197266%2C%22https_required%22%3Afalse%2C%22privileged%22%3Atrue%2C%22user_id%22%3A406308853%2C%22version%22%3A2%2C%22vod_id%22%3A447362459%7D
Signature: 10f95e1ca4c7582c8338bf52a04dac8e746f8686
Sub-Only: Yes
Privileged: Yes

Creating temporary download directory 'C:\Users\zar\AppData\Local\Temp\TL_97ea16de-afae-4bbb-af2e-9117f497c65f'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\zar\AppData\Local\Temp\TL_97ea16de-afae-4bbb-af2e-9117f497c65f'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment] 2019-07-03 12:15
I cannot test this VOD since it is sub-only. Please provide another example!

**Comment by Franiac** [comment] 2019-07-03 12:18
Duplicate of #345

**Closed by Franiac** 2019-07-03 12:18 UTC
